export { PLAN_MARKER } from './settingsRegistry.js';

export {
  type SettingCategory,
  type SettingSpec,
  type ValidationResult,
  type SeparatedSettings,
  type DirectSettingSpec,
  SETTINGS_REGISTRY,
  separateSettings,
  getSettingSpec,
  resolveAlias,
  validateSetting,
  normalizeSetting,
  parseSetting,
  getProfilePersistableKeys,
  getSettingHelp,
  getCompletionOptions,
  getAllSettingKeys,
  getValidationHelp,
  getAutocompleteSuggestions,
  getProtectedSettingKeys,
  getProviderConfigKeys,
  getDirectSettingSpecs,
} from './settingsRegistry.js';
