/**
 * @license
 * Copyright 2025 Vybestack LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Behavioral tests for createDetachedAutoPromptClient (#2378 review
 * remediation — Finding 4).
 *
 * These tests verify the delegation contract: the function delegates to the
 * source's `createDetachedAgentClient` method, returning the exact client it
 * produces, and throws a descriptive error when the method is absent.
 */

import { describe, expect, it } from 'vitest';
import type { AgentClientContract } from '@vybestack/llxprt-code-core';
import {
  createDetachedAutoPromptClient,
  type DetachedAutoPromptClientSource,
} from './autoPromptDetachedClient.js';

function makeFakeClient(id: string): AgentClientContract {
  return { id } as unknown as AgentClientContract;
}

describe('createDetachedAutoPromptClient', () => {
  it('delegates to the source createDetachedAgentClient and returns its result', () => {
    const expectedClient = makeFakeClient('detached-1');
    const source: DetachedAutoPromptClientSource = {
      createDetachedAgentClient: () => expectedClient,
    };

    const result = createDetachedAutoPromptClient(source);

    expect(result).toBe(expectedClient);
  });

  it('invokes createDetachedAgentClient with no runtimeId argument (id is generated by core)', () => {
    // createDetachedAutoPromptClient takes only a source — it deliberately does
    // NOT accept or forward a runtimeId. Core's createDetachedAgentClient
    // generates a fresh detached id when none is supplied, so the CLI helper
    // must call it with ZERO arguments and let core own id generation.
    let callArgCount = -1;
    let capturedRuntimeId: string | undefined;
    const expectedClient = makeFakeClient('detached-2');
    const source: DetachedAutoPromptClientSource = {
      createDetachedAgentClient: (...args: [runtimeId?: string]) => {
        callArgCount = args.length;
        capturedRuntimeId = args[0];
        return expectedClient;
      },
    };

    const result = createDetachedAutoPromptClient(source);

    expect(result).toBe(expectedClient);
    // Called with no positional arguments; the id is therefore omitted.
    expect(callArgCount).toBe(0);
    expect(capturedRuntimeId).toBeUndefined();
  });

  it('throws a descriptive error when createDetachedAgentClient is absent', () => {
    const source: DetachedAutoPromptClientSource = {};

    expect(() => createDetachedAutoPromptClient(source)).toThrow(
      /createDetachedAgentClient is not available/,
    );
  });

  it('throws a descriptive error when createDetachedAgentClient is not a function', () => {
    const source = {
      createDetachedAgentClient: 'not-a-function',
    } as unknown as DetachedAutoPromptClientSource;

    expect(() => createDetachedAutoPromptClient(source)).toThrow(
      /createDetachedAgentClient is not available/,
    );
  });
});
