/**
 * @license
 * Copyright 2025 Vybestack LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import type { MediaBlock } from '@vybestack/llxprt-code-core/services/history/IContent.js';
import {
  isUrlEncodedMediaBlock,
  type MediaCategory,
} from '../utils/mediaUtils.js';

/**
 * The default Anthropic API endpoint used when no explicit base URL is
 * configured. The AnthropicProvider falls back to this in executeApiCall;
 * stamping and stripping logic must use the same default so that turns
 * generated by native Anthropic are stamped with an endpoint that can be
 * compared against third-party Anthropic-compatible endpoints (e.g. z.ai).
 */
export const ANTHROPIC_DEFAULT_BASE_URL = 'https://api.anthropic.com';

/**
 * Determines whether a base URL points to the native Anthropic API
 * (anthropic.com or a subdomain thereof, e.g. api.anthropic.com).
 *
 * Returns `true` for an undefined/empty base URL (the default endpoint is
 * Anthropic). Returns `false` for third-party Anthropic-compatible endpoints
 * such as z.ai, suffix-spoofing hosts, and malformed URLs.
 *
 * Note: the bare apex domain `anthropic.com` (the marketing site) also
 * matches. This is intentional for backwards compatibility — OAuth
 * credentials are scoped to the Anthropic account, not a specific subdomain.
 *
 * Used by OAuth eligibility gating (#2411) and prompt-cache format gating
 * (#2410): third-party endpoints reject the Anthropic cache_control array
 * format and must not receive OAuth handshakes.
 */
export function isAnthropicOAuthBaseURL(baseURL?: string): boolean {
  if (baseURL === undefined || baseURL.trim() === '') {
    return true;
  }
  try {
    const host = new URL(baseURL).hostname.toLowerCase();
    return host === 'anthropic.com' || host.endsWith('.anthropic.com');
  } catch {
    return false;
  }
}

/**
 * Determines whether a base URL points at zai's Anthropic-compatible API
 * (z.ai or bigmodel.cn, including subdomains such as api.z.ai and
 * open.bigmodel.cn).
 *
 * Unlike {@link isAnthropicOAuthBaseURL}, an undefined/empty base URL returns
 * `false`: the zai capability restrictions keyed off this test never apply to
 * the default native Anthropic endpoint.
 *
 * zai rejects `source:{type:'url'}` image blocks with a 400 (#3693), so
 * request preparation uses this test to swap url-encoded image blocks for the
 * unsupported-media text placeholder on zai hosts only.
 */
export function isZaiAnthropicEndpoint(baseURL?: string): boolean {
  if (baseURL === undefined || baseURL.trim() === '') {
    return false;
  }
  try {
    // Strip the DNS root label: WHATWG URL parsing preserves a terminal dot
    // ('https://api.z.ai./' → hostname 'api.z.ai.'), which would otherwise
    // fail the suffix match and skip the zai media restrictions.
    const host = new URL(baseURL.trim()).hostname
      .toLowerCase()
      .replace(/\.$/, '');
    return (
      matchesHostSuffix(host, 'z.ai') || matchesHostSuffix(host, 'bigmodel.cn')
    );
  } catch {
    return false;
  }
}

/**
 * Media-support predicate for `collectUnsupportedMedia` on the Anthropic
 * path: pdf and image blocks are supported, except that url-encoded image
 * blocks count as unsupported on zai endpoints (#3693), where the converter
 * serializes them as placeholders and the projection must match. Takes the
 * endpoint base URL and applies the zai test itself so call sites stay a
 * single expression.
 */
export function createMediaSupportPredicate(
  baseURL: string | undefined,
): (block: MediaBlock, category: MediaCategory) => boolean {
  const zaiEndpoint = isZaiAnthropicEndpoint(baseURL);
  return (block, category) => {
    if (category === 'pdf') {
      return true;
    }
    if (category !== 'image') {
      return false;
    }
    return !(zaiEndpoint && isUrlEncodedMediaBlock(block));
  };
}

function matchesHostSuffix(hostname: string, suffix: string): boolean {
  return hostname === suffix || hostname.endsWith(`.${suffix}`);
}
