/**
 * @license
 * Copyright 2025 Vybestack LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Tests for cross-model thinking block stripping (issue #2335).
 *
 * Anthropic thinking-block signatures are model-specific: a thinking block
 * generated by model A must never be replayed to model B. These tests verify
 * that convertToAnthropicMessages drops model-bound thinking blocks when the
 * turn's metadata.model differs from the current request model.
 */

import { describe, it, expect } from 'vitest';
import type {
  IContent,
  ThinkingBlock,
} from '@vybestack/llxprt-code-core/services/history/IContent.js';
import { stampAiTurnModel } from '@vybestack/llxprt-code-core/services/history/IContent.js';
import { convertToAnthropicMessages } from './AnthropicMessageNormalizer.js';

type DebugLogger = { debug: (fn: () => string) => void };
const noopLogger: DebugLogger = { debug: () => {} };

const baseOptions = {
  isOAuth: false,
  reasoningEnabled: true,
  config: undefined,
  unprefixToolName: (name: string) => name,
};

function assistantWithThinking(
  model: string | undefined,
  signature: string,
  thought = 'previous reasoning',
): IContent {
  const content: IContent = {
    speaker: 'ai',
    blocks: [
      {
        type: 'thinking',
        thought,
        sourceField: 'thinking',
        signature,
      } as ThinkingBlock,
      { type: 'text', text: 'hello' },
    ],
  };
  if (model !== undefined) {
    content.metadata = { model };
  }
  return content;
}

function findAssistantMessages(
  messages: ReturnType<typeof convertToAnthropicMessages>,
) {
  return messages.filter((m) => m.role === 'assistant');
}

type AssistantContentBlock = { type?: string; text?: string };

function assistantContentBlocks(
  messages: ReturnType<typeof convertToAnthropicMessages>,
): AssistantContentBlock[] {
  const blocks: AssistantContentBlock[] = [];
  for (const m of findAssistantMessages(messages)) {
    if (Array.isArray(m.content)) {
      blocks.push(...(m.content as AssistantContentBlock[]));
    } else if (typeof m.content === 'string') {
      // Text-only assistant messages collapse to a string content payload.
      blocks.push({ type: 'text', text: m.content });
    }
  }
  return blocks;
}

function flatAssistantBlocks(
  messages: ReturnType<typeof convertToAnthropicMessages>,
): Array<{ type: string; [k: string]: unknown }> {
  return assistantContentBlocks(messages) as Array<{
    type: string;
    [k: string]: unknown;
  }>;
}

function assistantText(
  messages: ReturnType<typeof convertToAnthropicMessages>,
): string[] {
  return assistantContentBlocks(messages)
    .filter((b) => b.type === 'text' && typeof b.text === 'string')
    .map((b) => b.text as string);
}

describe('convertToAnthropicMessages - cross-model thinking strip (issue #2335)', () => {
  it('replays thinking unchanged on SAME-model turn', () => {
    const contents: IContent[] = [
      { speaker: 'human', blocks: [{ type: 'text', text: 'hi' }] },
      assistantWithThinking('claude-opus-4-8', 'sig-A'),
    ];

    const messages = convertToAnthropicMessages(contents, {
      ...baseOptions,
      currentModel: 'claude-opus-4-8',
      logger: noopLogger,
    });

    const blocks = flatAssistantBlocks(messages);
    const thinking = blocks.find((b) => b.type === 'thinking') as
      | { type: 'thinking'; thinking: string; signature?: string }
      | undefined;

    expect(thinking).toBeDefined();
    expect(thinking?.thinking).toBe('previous reasoning');
    expect(thinking?.signature).toBe('sig-A');
    expect(blocks.some((b) => b.type === 'text')).toBe(true);
  });

  it('drops thinking blocks on CROSS-model turn but preserves text', () => {
    const contents: IContent[] = [
      { speaker: 'human', blocks: [{ type: 'text', text: 'hi' }] },
      assistantWithThinking('claude-opus-4-8', 'sig-A'),
    ];

    const messages = convertToAnthropicMessages(contents, {
      ...baseOptions,
      currentModel: 'claude-fable-5',
      logger: noopLogger,
    });

    const blocks = flatAssistantBlocks(messages);
    expect(blocks.some((b) => b.type === 'thinking')).toBe(false);
    expect(blocks.some((b) => b.type === 'redacted_thinking')).toBe(false);
    expect(assistantText(messages)).toContain('hello');
  });

  it('drops thinking but preserves tool_use and tool_result adjacency on cross-model', () => {
    const contents: IContent[] = [
      { speaker: 'human', blocks: [{ type: 'text', text: 'list files' }] },
      {
        speaker: 'ai',
        metadata: { model: 'claude-opus-4-8' },
        blocks: [
          {
            type: 'thinking',
            thought: 'planning',
            sourceField: 'thinking',
            signature: 'sig-A',
          } as ThinkingBlock,
          {
            type: 'tool_call',
            id: 'tool_001',
            name: 'list_directory',
            parameters: { path: '/tmp' },
          },
        ],
      },
      {
        speaker: 'tool',
        blocks: [
          {
            type: 'tool_response',
            callId: 'tool_001',
            toolName: 'list_directory',
            result: { files: ['a.txt'] },
          },
        ],
      },
      { speaker: 'human', blocks: [{ type: 'text', text: 'thanks' }] },
    ];

    const messages = convertToAnthropicMessages(contents, {
      ...baseOptions,
      currentModel: 'claude-fable-5',
      logger: noopLogger,
    });

    // Find the assistant message with tool_use.
    const assistantWithTool = messages.find(
      (m) =>
        m.role === 'assistant' &&
        Array.isArray(m.content) &&
        m.content.some((b) => (b as { type?: string }).type === 'tool_use'),
    );
    expect(assistantWithTool).toBeDefined();

    const blocks = assistantWithTool!.content as Array<{
      type: string;
      [k: string]: unknown;
    }>;
    expect(blocks.some((b) => b.type === 'thinking')).toBe(false);
    expect(blocks.some((b) => b.type === 'redacted_thinking')).toBe(false);

    const toolUse = blocks.find((b) => b.type === 'tool_use') as
      | { type: 'tool_use'; id: string; name: string }
      | undefined;
    expect(toolUse).toBeDefined();
    expect(toolUse?.id).toBe('toolu_tool_001');
    expect(toolUse?.name).toBe('list_directory');

    // The immediately following message must be the tool_result user message.
    const toolUseIndex = messages.indexOf(assistantWithTool!);
    const next = messages[toolUseIndex + 1];
    expect(next).toBeDefined();
    expect(next.role).toBe('user');
    expect(
      (next.content as Array<{ type: string }>).some(
        (b) => b.type === 'tool_result',
      ),
    ).toBe(true);
  });

  it('strips thinking in an OPEN tool loop: cross-model final assistant turn + just-closed tool_response', () => {
    // Open/just-closed tool-loop shape: the trailing assistant turn carries a
    // signed thinking block + a tool_use, and the LAST content is the matching
    // tool_response from the tool speaker (the loop is open, not yet followed
    // by a fresh user turn).
    //
    // Stripping the cross-model signature here is correct and strictly no worse
    // than the closed-loop case: replaying a signature minted by a different
    // model to the current model always yields an Anthropic 400
    // (Invalid signature in thinking block), so keeping it could never succeed.
    // Additionally, model switches cannot occur mid-loop in this codebase —
    // loops are closed synthetically before the next request is built — so the
    // currentModel in effect at the next request equals the model that will
    // emit any subsequent thinking, never a third party.
    const contents: IContent[] = [
      { speaker: 'human', blocks: [{ type: 'text', text: 'read the file' }] },
      {
        speaker: 'ai',
        metadata: { model: 'claude-opus-4-8' },
        blocks: [
          {
            type: 'thinking',
            thought: 'deciding which tool to call',
            sourceField: 'thinking',
            signature: 'sig-A',
          } as ThinkingBlock,
          {
            type: 'tool_call',
            id: 'tool_002',
            name: 'read_file',
            parameters: { path: '/tmp/note.txt' },
          },
        ],
      },
      {
        speaker: 'tool',
        blocks: [
          {
            type: 'tool_response',
            callId: 'tool_002',
            toolName: 'read_file',
            result: { contents: 'hello world' },
          },
        ],
      },
    ];

    const messages = convertToAnthropicMessages(contents, {
      ...baseOptions,
      currentModel: 'claude-fable-5',
      logger: noopLogger,
    });

    // No thinking/redacted_thinking block anywhere.
    const blocks = flatAssistantBlocks(messages);
    expect(blocks.some((b) => b.type === 'thinking')).toBe(false);
    expect(blocks.some((b) => b.type === 'redacted_thinking')).toBe(false);
    // No block anywhere carries the cross-model signature.
    expect(
      blocks.some(
        (b) =>
          (b as { signature?: unknown }).signature === 'sig-A' ||
          (b as { data?: unknown }).data === 'sig-A',
      ),
    ).toBe(false);

    // The trailing assistant message still contains the tool_use with the same
    // id (post-normalization prefix) and name.
    const trailingAssistant = findAssistantMessages(messages).find((m) =>
      (Array.isArray(m.content)
        ? (m.content as Array<{ type?: string }>)
        : []
      ).some((b) => b.type === 'tool_use'),
    );
    expect(trailingAssistant).toBeDefined();
    const toolUse = (
      trailingAssistant!.content as Array<{
        type: string;
        [k: string]: unknown;
      }>
    ).find((b) => b.type === 'tool_use') as
      | { type: 'tool_use'; id: string; name: string }
      | undefined;
    expect(toolUse).toBeDefined();
    expect(toolUse?.id).toBe('toolu_tool_002');
    expect(toolUse?.name).toBe('read_file');

    // The following user message carries the matching tool_result.
    const assistantIndex = messages.indexOf(trailingAssistant!);
    const toolResultMessage = messages[assistantIndex + 1];
    expect(toolResultMessage).toBeDefined();
    expect(toolResultMessage.role).toBe('user');
    expect(
      (toolResultMessage.content as Array<{ type: string }>).some(
        (b) => b.type === 'tool_result',
      ),
    ).toBe(true);
  });

  it('leaves thinking untouched when metadata.model is unset (unknown turn)', () => {
    const contents: IContent[] = [
      { speaker: 'human', blocks: [{ type: 'text', text: 'hi' }] },
      assistantWithThinking(undefined, 'sig-A'),
    ];

    const messages = convertToAnthropicMessages(contents, {
      ...baseOptions,
      currentModel: 'claude-fable-5',
      logger: noopLogger,
    });

    const blocks = flatAssistantBlocks(messages);
    const thinking = blocks.find((b) => b.type === 'thinking') as
      | { type: 'thinking'; thinking: string; signature?: string }
      | undefined;
    expect(thinking).toBeDefined();
    expect(thinking?.signature).toBe('sig-A');
  });

  it('is fully backward compatible when currentModel option is omitted', () => {
    const contents: IContent[] = [
      { speaker: 'human', blocks: [{ type: 'text', text: 'hi' }] },
      assistantWithThinking('claude-opus-4-8', 'sig-A'),
    ];

    const messages = convertToAnthropicMessages(contents, {
      ...baseOptions,
      logger: noopLogger,
    });

    const blocks = flatAssistantBlocks(messages);
    const thinking = blocks.find((b) => b.type === 'thinking') as
      | { type: 'thinking'; thinking: string; signature?: string }
      | undefined;
    expect(thinking).toBeDefined();
    expect(thinking?.signature).toBe('sig-A');
  });

  it('drops a thinking-only cross-model turn entirely', () => {
    const contents: IContent[] = [
      { speaker: 'human', blocks: [{ type: 'text', text: 'first' }] },
      {
        speaker: 'ai',
        metadata: { model: 'claude-opus-4-8' },
        blocks: [
          {
            type: 'thinking',
            thought: 'only reasoning, no visible output',
            sourceField: 'thinking',
            signature: 'sig-A',
          } as ThinkingBlock,
        ],
      },
      { speaker: 'human', blocks: [{ type: 'text', text: 'second' }] },
    ];

    const messages = convertToAnthropicMessages(contents, {
      ...baseOptions,
      currentModel: 'claude-fable-5',
      logger: noopLogger,
    });

    // The thinking-only assistant turn must be gone.
    const assistant = findAssistantMessages(messages);
    expect(assistant).toHaveLength(0);

    // Surrounding user turns still form a valid alternating sequence.
    expect(messages.every((m) => m.role === 'user')).toBe(true);
  });

  it('does not leak the cross-model signature via redacted_thinking under strip policy all', () => {
    const contents: IContent[] = [
      { speaker: 'human', blocks: [{ type: 'text', text: 'hi' }] },
      assistantWithThinking('claude-opus-4-8', 'sig-A'),
    ];

    const messages = convertToAnthropicMessages(contents, {
      ...baseOptions,
      currentModel: 'claude-fable-5',
      stripFromContext: 'all',
      logger: noopLogger,
    });

    const blocks = flatAssistantBlocks(messages);
    expect(blocks.some((b) => b.type === 'thinking')).toBe(false);
    expect(blocks.some((b) => b.type === 'redacted_thinking')).toBe(false);
    expect(
      blocks.some(
        (b) =>
          (b as { data?: unknown }).data === 'sig-A' ||
          (b as { signature?: unknown }).signature === 'sig-A',
      ),
    ).toBe(false);
  });

  it('keeps a non-thinking sourceField thinking block as text on a cross-model turn', () => {
    const contents: IContent[] = [
      { speaker: 'human', blocks: [{ type: 'text', text: 'hi' }] },
      {
        speaker: 'ai',
        metadata: { model: 'claude-opus-4-8' },
        blocks: [
          {
            type: 'thinking',
            thought: 'reasoning content from elsewhere',
            sourceField: 'reasoning_content',
          } as ThinkingBlock,
          { type: 'text', text: 'hello' },
        ],
      },
    ];

    const messages = convertToAnthropicMessages(contents, {
      ...baseOptions,
      currentModel: 'claude-fable-5',
      logger: noopLogger,
    });

    const blocks = flatAssistantBlocks(messages);
    // No model-bound thinking/redacted_thinking emitted.
    expect(blocks.some((b) => b.type === 'thinking')).toBe(false);
    expect(blocks.some((b) => b.type === 'redacted_thinking')).toBe(false);
    // The reasoning_content is kept as text.
    expect(
      blocks.some(
        (b) =>
          b.type === 'text' && b.text === 'reasoning content from elsewhere',
      ),
    ).toBe(true);
  });
});

/**
 * End-to-end chain: a freshly generated AI turn stamped at the recording
 * boundary (via stampAiTurnModel) flows through convertToAnthropicMessages.
 * Cross-model → thinking stripped; same-model → signature byte-for-byte
 * preserved. This proves the stamped-at-recording → stripped-at-conversion
 * property holds using the real helper as the input producer (issue #2335).
 */
describe('stampAiTurnModel → convertToAnthropicMessages end-to-end (issue #2335)', () => {
  function freshlyGeneratedAiTurn(): IContent {
    // Unstamped, exactly as the recording boundary receives it before stamping.
    return {
      speaker: 'ai',
      blocks: [
        {
          type: 'thinking',
          thought: 'previous reasoning',
          sourceField: 'thinking',
          signature: 'sig-A',
        } as ThinkingBlock,
        { type: 'text', text: 'hello' },
      ],
    };
  }

  it('strips thinking when the stamped origin differs from currentModel', () => {
    const stamped = stampAiTurnModel(
      freshlyGeneratedAiTurn(),
      'claude-opus-4-8',
    );
    expect(stamped.metadata?.model).toBe('claude-opus-4-8');

    const messages = convertToAnthropicMessages(
      [{ speaker: 'human', blocks: [{ type: 'text', text: 'hi' }] }, stamped],
      {
        ...baseOptions,
        currentModel: 'claude-fable-5',
        logger: noopLogger,
      },
    );

    const blocks = flatAssistantBlocks(messages);
    expect(blocks.some((b) => b.type === 'thinking')).toBe(false);
    expect(blocks.some((b) => b.type === 'redacted_thinking')).toBe(false);
    expect(assistantText(messages)).toContain('hello');
  });

  it('preserves the signature byte-for-byte on the same model', () => {
    const stamped = stampAiTurnModel(
      freshlyGeneratedAiTurn(),
      'claude-opus-4-8',
    );

    const messages = convertToAnthropicMessages(
      [{ speaker: 'human', blocks: [{ type: 'text', text: 'hi' }] }, stamped],
      {
        ...baseOptions,
        currentModel: 'claude-opus-4-8',
        logger: noopLogger,
      },
    );

    const blocks = flatAssistantBlocks(messages);
    const thinking = blocks.find((b) => b.type === 'thinking') as
      | { type: 'thinking'; thinking: string; signature?: string }
      | undefined;
    expect(thinking).toBeDefined();
    expect(thinking?.thinking).toBe('previous reasoning');
    expect(thinking?.signature).toBe('sig-A');
  });

  it('leaves an unstamped turn untouched (import-safety at conversion time)', () => {
    const unstamped = freshlyGeneratedAiTurn();
    expect(unstamped.metadata?.model).toBeUndefined();

    const messages = convertToAnthropicMessages(
      [{ speaker: 'human', blocks: [{ type: 'text', text: 'hi' }] }, unstamped],
      {
        ...baseOptions,
        currentModel: 'claude-fable-5',
        logger: noopLogger,
      },
    );

    const blocks = flatAssistantBlocks(messages);
    const thinking = blocks.find((b) => b.type === 'thinking') as
      | { type: 'thinking'; signature?: string }
      | undefined;
    expect(thinking?.signature).toBe('sig-A');
  });
});
