/**
 * @license
 * Copyright 2025 Vybestack LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactPlugin from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import prettierConfig from 'eslint-config-prettier';
import importPlugin from 'eslint-plugin-import';
import jest from 'eslint-plugin-jest';
import sonarjs from 'eslint-plugin-sonarjs';
import eslintComments from 'eslint-plugin-eslint-comments';
import globals from 'globals';
import headers from 'eslint-plugin-headers';
import reactRenderSafety from './eslint-rules/react-render-safety.js';
import noInlineDeps from './eslint-rules/no-inline-deps.js';
import inkTextColorRequired from './eslint-rules/ink-text-color-required.js';
import path from 'node:path';
import url from 'node:url';

// --- ESM way to get __dirname ---
const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// --- ---

// Determine the monorepo root (assuming eslint.config.js is at the root)
const projectRoot = __dirname;

export default tseslint.config(
  {
    // Global ignores
    ignores: [
      'node_modules/*',
      '.yalc/**',
      '**/.yalc/**',
      'yalc.lock',
      '**/yalc.lock',
      '.worktrees/**',
      '.integration-tests/**',
      'eslint.config.js',
      'packages/**/dist/**',
      'bundle/**',
      // Generated publish artifact (issue #2999): the prebuilt CLI bundle is
      // build output, not source, and is regenerated by `npm run bundle:cli`.
      'packages/**/bundle/**',
      'packages/cli/src/test-*.ts',
      'packages/cli/src/test-*.tsx',
      'packages/cli/src/debug-*.ts',
      'packages/cli/src/debug-*.tsx',
      'packages/cli/src/generated/**',
      'debug-*.js',
      'test-*.js',
      'test-*.mjs',
      'suppress-deprecations.mjs',
      'reference/**',
      'research/**',
      'tmp/**',
      'package/bundle/**',
      '.integration-tests/**',
      '.stryker-tmp/**',
      '**/.stryker-tmp/**',
      'project-plans/**',
      'packages/opentui/**',
      'packages/ui/**',
      'packages/lsp/**',
    ],
  },
  {
    // Issue #2079: stale disable directives are policy failures, not warnings.
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  reactHooks.configs['recommended-latest'],
  reactPlugin.configs.flat.recommended,
  reactPlugin.configs.flat['jsx-runtime'], // Add this if you are using React 17+
  {
    // Settings for eslint-plugin-react
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  {
    // Import specific config
    files: ['packages/cli/src/**/*.{ts,tsx}'], // Target only TS/TSX in the cli package
    plugins: {
      import: importPlugin,
    },
    settings: {
      'import/resolver': {
        node: true,
      },
    },
    rules: {
      ...importPlugin.configs.recommended.rules,
      ...importPlugin.configs.typescript.rules,
      'import/no-default-export': 'error',
      'import/no-unresolved': 'off', // Disable for now, can be noisy with monorepos/paths
    },
  },
  {
    // General overrides and rules for the project (TS/TSX files)
    files: ['packages/*/src/**/*.{ts,tsx}'], // Target only TS/TSX in the cli package
    plugins: {
      import: importPlugin,
      sonarjs,
      'eslint-comments': eslintComments,
    },
    settings: {
      'import/resolver': {
        node: true,
      },
    },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: {
          allowDefaultProject: ['packages/core/src/prompts/*.d.ts'],
        },
        tsconfigRootDir: projectRoot,
      },
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
    rules: {
      // General Best Practice Rules (subset adapted for flat config)
      '@typescript-eslint/array-type': ['error', { default: 'array-simple' }],
      'arrow-body-style': ['error', 'as-needed'],
      curly: ['error', 'multi-line'],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        { assertionStyle: 'as' },
      ],
      '@typescript-eslint/explicit-member-accessibility': [
        'error',
        { accessibility: 'no-public' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-inferrable-types': [
        'error',
        { ignoreParameters: true, ignoreProperties: true },
      ],
      '@typescript-eslint/no-namespace': ['error', { allowDeclarations: true }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Prevent async errors from bypassing catch handlers
      '@typescript-eslint/return-await': ['error', 'in-try-catch'],
      'import/no-internal-modules': [
        'error',
        {
          allow: [
            'react-dom/test-utils',
            'memfs/lib/volume.js',
            'vscode-jsonrpc/node.js',
            'yargs/**',
            '@anthropic-ai/sdk/**',
            'ajv/dist/2020.js',
            '**/generated/**',
            '**/prompts/**',
          ],
        },
      ],
      'import/no-relative-packages': 'error',
      'no-cond-assign': 'error',
      'no-debugger': 'error',
      'no-duplicate-case': 'error',
      'no-restricted-syntax': [
        'error',
        {
          selector: 'CallExpression[callee.name="require"]',
          message: 'Avoid using require(). Use ES6 imports instead.',
        },
        {
          selector: 'ThrowStatement > Literal:not([value=/^\\w+Error:/])',
          message:
            'Do not throw string literals or non-Error objects. Throw new Error("...") instead.',
        },
      ],
      'no-unsafe-finally': 'error',
      'no-unused-expressions': 'off', // Disable base rule
      '@typescript-eslint/no-unused-expressions': [
        // Enable TS version
        'error',
        { allowShortCircuit: true, allowTernary: true },
      ],
      'no-var': 'error',
      'object-shorthand': 'error',
      'one-var': ['error', 'never'],
      'prefer-arrow-callback': 'error',
      'prefer-const': ['error', { destructuring: 'all' }],
      'no-console': 'error',
      radix: 'error',
      'default-case': 'error',
      '@typescript-eslint/await-thenable': ['error'],
      '@typescript-eslint/no-floating-promises': ['error'],
      '@typescript-eslint/no-unnecessary-type-assertion': ['error'],

      // --- Strict rules modeled after lsp/ui packages (enabled as warnings for core/cli) ---

      // Strict TypeScript rules
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/strict-boolean-expressions': [
        'error',
        {
          allowString: true,
          allowNumber: false,
          allowNullableObject: true,
          allowNullableBoolean: false,
          allowNullableString: true,
          allowNullableNumber: false,
          allowAny: false,
        },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports' },
      ],
      '@typescript-eslint/switch-exhaustiveness-check': [
        'error',
        { considerDefaultExhaustiveForUnions: true },
      ],
      '@typescript-eslint/no-unnecessary-condition': 'error',
      '@typescript-eslint/prefer-nullish-coalescing': 'error',
      '@typescript-eslint/prefer-optional-chain': 'error',

      // General code quality
      'no-else-return': 'error',
      'no-lonely-if': 'error',
      'no-unneeded-ternary': 'error',

      // Complexity limits
      complexity: ['error', 25],
      'max-lines': [
        'error',
        { max: 800, skipBlankLines: true, skipComments: true },
      ],
      'max-lines-per-function': [
        'error',
        { max: 80, skipBlankLines: true, skipComments: true },
      ],

      // Issue #2079: warning-only SonarJS recommendations are not permitted
      // because lint:ci uses --max-warnings 0. Start from off, then promote
      // project-signal rules below to error. Future off decisions must be
      // explicit and justified so the guard in scripts/check-eslint-guard.ts
      // can reject accidental policy weakening.
      ...Object.fromEntries(
        Object.entries(sonarjs.configs.recommended.rules ?? {}).map(
          ([rule, config]) => [
            rule,
            Array.isArray(config) ? ['off', ...config.slice(1)] : 'off', // eslint-policy-allow-off: #2079
          ],
        ),
      ),
      'sonarjs/cognitive-complexity': ['error', 30],
      'sonarjs/todo-tag': 'error',
      'sonarjs/no-ignored-exceptions': 'error',
      // Issue #2113: sonarjs/regular-expr is a deprecated, non-recommended
      // blanket review heuristic for ordinary regex usage. Keep targeted regex
      // correctness and ReDoS rules enabled where they provide actionable
      // signal rather than source-level suppression comments.
      'sonarjs/regular-expr': 'off', // eslint-policy-allow-off: #2113 deprecated blanket regex heuristic
      'sonarjs/slow-regex': 'error',
      'sonarjs/no-invalid-regexp': 'error',
      'sonarjs/stateful-regex': 'error',
      'sonarjs/unicode-aware-regex': 'error',
      'sonarjs/no-regex-spaces': 'error',
      'no-control-regex': 'error',
      // Issue #2079: this CLI intentionally invokes user/platform tools such as
      // git, shells, editors, and ripgrep. These rules are not useful signal.
      'sonarjs/os-command': 'off', // eslint-policy-allow-off: #2079
      'sonarjs/no-os-command-from-path': 'off', // eslint-policy-allow-off: #2079
      'sonarjs/no-all-duplicated-branches': 'error',
      'sonarjs/no-duplicated-branches': 'error',
      'sonarjs/no-identical-functions': 'error',
      'sonarjs/no-inconsistent-returns': 'error',
      'sonarjs/no-collapsible-if': 'error',
      'sonarjs/nested-control-flow': 'error',
      'sonarjs/expression-complexity': 'error',
      'sonarjs/no-nested-conditional': 'error',
      'sonarjs/too-many-break-or-continue-in-loop': 'error',

      'sonarjs/function-return-type': 'off',
      'sonarjs/no-wildcard-import': 'off',
      'sonarjs/file-header': 'off',

      // Irrelevant SonarJS rules for this Node.js CLI codebase

      // AWS infrastructure rules — no CloudFormation/Terraform/CDK usage
      'sonarjs/aws-apigateway-public-api': 'off',
      'sonarjs/aws-ec2-rds-dms-public': 'off',
      'sonarjs/aws-ec2-unencrypted-ebs-volume': 'off',
      'sonarjs/aws-efs-unencrypted': 'off',
      'sonarjs/aws-iam-all-privileges': 'off',
      'sonarjs/aws-iam-all-resources-accessible': 'off',
      'sonarjs/aws-iam-privilege-escalation': 'off',
      'sonarjs/aws-iam-public-access': 'off',
      'sonarjs/aws-opensearchservice-domain': 'off',
      'sonarjs/aws-rds-unencrypted-databases': 'off',
      'sonarjs/aws-restricted-ip-admin-access': 'off',
      'sonarjs/aws-s3-bucket-granted-access': 'off',
      'sonarjs/aws-s3-bucket-insecure-http': 'off',
      'sonarjs/aws-s3-bucket-public-access': 'off',
      'sonarjs/aws-s3-bucket-server-encryption': 'off',
      'sonarjs/aws-s3-bucket-versioning': 'off',
      'sonarjs/aws-sagemaker-unencrypted-notebook': 'off',
      'sonarjs/aws-sns-unencrypted-topics': 'off',
      'sonarjs/aws-sqs-unencrypted-queue': 'off',

      // Web security / browser / HTTP rules — CLI does not serve HTTP, set cookies, or render HTML
      'sonarjs/certificate-transparency': 'off',
      'sonarjs/content-length': 'off',
      'sonarjs/content-security-policy': 'off',
      'sonarjs/cookie-no-httponly': 'off',
      'sonarjs/cookies': 'off',
      'sonarjs/cors': 'off',
      'sonarjs/csrf': 'off',
      'sonarjs/disabled-auto-escaping': 'off',
      'sonarjs/disabled-resource-integrity': 'off',
      'sonarjs/dns-prefetching': 'off',
      'sonarjs/frame-ancestors': 'off',
      'sonarjs/hidden-files': 'off',
      'sonarjs/insecure-cookie': 'off',
      'sonarjs/link-with-target-blank': 'off',
      'sonarjs/no-clear-text-protocols': 'off',
      'sonarjs/no-ip-forward': 'off',
      'sonarjs/no-mime-sniff': 'off',
      'sonarjs/no-mixed-content': 'off',
      'sonarjs/no-referrer-policy': 'off',
      'sonarjs/no-session-cookies-on-static-assets': 'off',
      'sonarjs/post-message': 'off',
      'sonarjs/session-regeneration': 'off',
      'sonarjs/strict-transport-security': 'off',
      'sonarjs/unverified-certificate': 'off',
      'sonarjs/unverified-hostname': 'off',
      'sonarjs/weak-ssl': 'off',
      'sonarjs/x-powered-by': 'off',

      // HTML/DOM/Accessibility rules — no server-rendered HTML or DOM manipulation
      'sonarjs/no-table-as-layout': 'off',
      'sonarjs/object-alt-content': 'off',
      'sonarjs/table-header': 'off',
      'sonarjs/table-header-reference': 'off',
      'sonarjs/no-intrusive-permissions': 'off',

      // Framework-specific rules — Angular/Vue not used; React SonarJS rules overlap with eslint-plugin-react
      'sonarjs/no-angular-bypass-sanitization': 'off',
      'sonarjs/no-vue-bypass-sanitization': 'off',
      'sonarjs/chai-determinate-assertion': 'off',
      'sonarjs/no-hook-setter-in-body': 'off',
      'sonarjs/no-useless-react-setstate': 'off',
      'sonarjs/prefer-read-only-props': 'off',
      'sonarjs/no-uniq-key': 'off',
      'sonarjs/jsx-no-leaked-render': 'off',

      // Database/SQL rules — no SQL or database usage
      'sonarjs/sql-queries': 'off',
      'sonarjs/web-sql-database': 'off',

      // Other irrelevant rules
      'sonarjs/review-blockchain-mnemonic': 'off',
      'sonarjs/xml-parser-xxe': 'off',
      'sonarjs/xpath': 'off',
      'sonarjs/file-uploads': 'off',

      // Expensive heuristic — NLP analysis on comments with no value for this codebase
      'sonarjs/no-commented-code': 'off',

      // TypeScript-incompatible rules — SonarJS doesn't understand TS global types
      'sonarjs/no-reference-error': 'off', // Flags NodeJS, describe, it, beforeEach as undefined

      // CLI-inappropriate rules — this is a CLI tool, not a web server
      'sonarjs/process-argv': 'off', // CLI needs command line args
      'sonarjs/standard-input': 'off', // CLI needs stdin for pipes
      'sonarjs/publicly-writable-directories': 'off', // CLI needs temp files
      'sonarjs/sockets': 'off', // MCP server uses stdio sockets

      // Module-scope misunderstanding — ESM module scope IS local scope
      'sonarjs/declarations-in-global-scope': 'off', // Top-level module decls are NOT global

      // API naming conflicts — tool API uses snake_case
      'sonarjs/variable-name': 'off', // file_path, old_string, new_string match tool params

      // Redundant with TypeScript-ESLint / other plugins (already have better versions)
      'sonarjs/cyclomatic-complexity': 'off', // ESLint 'complexity' already enabled
      'sonarjs/max-lines-per-function': 'off', // ESLint rule already enabled
      'sonarjs/max-lines': 'off', // ESLint rule already enabled
      'sonarjs/no-unused-vars': 'off', // @typescript-eslint/no-unused-vars handles this
      'sonarjs/no-unused-function-argument': 'off', // Covered by TS no-unused-vars with argsIgnorePattern
      'sonarjs/unused-import': 'off', // import plugin handles this
      'sonarjs/no-implicit-dependencies': 'off', // import plugin handles this
      'sonarjs/deprecation': 'off', // TypeScript compiler already warns on deprecated APIs

      // TypeScript-idiomatic patterns that SonarJS misunderstands
      'sonarjs/void-use': 'off', // Fire-and-forget promises are valid TS pattern
      'sonarjs/no-nested-functions': 'off', // Closures are idiomatic; nested-control-flow catches real issues
      'sonarjs/no-undefined-assignment': 'off', // TS uses undefined for optional properties (idiomatic)

      // Issue #1569c: Misfit SonarJS style rules turned off as documented noise.
      // These rules either conflict with Prettier, are pure stylistic preference,
      // or produce high false-positive rates with no correctness value for this codebase.
      'sonarjs/arrow-function-convention': 'off', // Conflicts with Prettier parens handling
      'sonarjs/no-duplicate-string': 'off', // 3-occurrence threshold produces pure noise
      'sonarjs/shorthand-property-grouping': 'off', // Pure ordering preference, no correctness value
      'sonarjs/elseif-without-else': 'off', // Pure style; conflicts with early-return pattern
      'sonarjs/max-union-size': 'off', // Discriminated unions legitimately exceed arbitrary limit
      'sonarjs/no-alphabetical-sort': 'off', // Heuristic is false-positive prone on typed arrays
      'sonarjs/prefer-regexp-exec': 'off', // String.match and RegExp.exec are both idiomatic
      'sonarjs/function-name': 'off', // Conflicts with TS class/method naming conventions
      'sonarjs/prefer-immediate-return': 'off', // Named intermediates improve readability/debuggability
      'sonarjs/pseudo-random': 'off', // CLI context: Math.random for IDs/jitter, not cryptography

      // Issue #2079: ESLint directive comments are policy controls, not code fixes.
      ...Object.fromEntries(
        Object.entries(eslintComments.configs.recommended.rules ?? {}).map(
          ([rule, config]) => [rule, Array.isArray(config) ? ['error', ...config.slice(1)] : 'error'],
        ),
      ),
      'eslint-comments/no-use': [
        'error',
        {
          allow: ['eslint-env', 'global', 'globals', 'exported'],
        },
      ],

      // --- End strict rules ---

      // Additional React-specific rules to prevent infinite loops
      'react-hooks/exhaustive-deps': [
        'error',
        {
          additionalHooks: '(useStateAndRef|useStableCallback|useStableGetter)',
        },
      ],
      'react/jsx-no-bind': [
        'error',
        {
          ignoreDOMComponents: false,
          ignoreRefs: true,
          allowArrowFunctions: false,
          allowFunctions: false,
          allowBind: false,
        },
      ],
      'react/jsx-no-constructed-context-values': 'error',
    },
  },

  // extra settings for scripts that we run directly with node
  // Issue #2079 temporary warning burn-down scopes. These were warning-only
  // before lint:ci started using --max-warnings 0 and are assigned to existing
  // cleanup areas instead of being left as warnings.
  {
    files: ['packages/cli/src/ui/**/*.{ts,tsx}'],
    rules: {
      'react/jsx-no-bind': 'off', // eslint-policy-allow-off: #2079 temporary #2087
    },
  },
  {
    files: ['packages/telemetry/src/debug/**/*.ts'],
    rules: {
      'no-console': 'off', // eslint-policy-allow-off: #2079 temporary #2089
    },
  },
  {
    files: ['./scripts/**/*.js', './scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        ...globals.node,
        process: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
  // ============================================================================
  // Issue #2282: Apply strict code-quality lint rules to scripts
  // ============================================================================
  // Build/dev scripts and their tests previously received only the base
  // ESLint recommended layer. This block extends the same SonarJS
  // maintainability, regex-correctness, and size/complexity guardrails that
  // protect packages/*/src to the scripts tree, so scripts are held to the
  // same code-quality bar.
  //
  // Deliberately NOT applied to scripts (documented rationale):
  //  - no-console: scripts are build/dev tooling that legitimately produces
  //    stdout/stderr output (unlike application source where logging goes
  //    through a logger).
  //  - Type-aware rules (@typescript-eslint/no-floating-promises,
  //    no-misused-promises, strict-boolean-expressions, etc.): the scripts
  //    tree has no tsconfig project, so type-aware analysis is unavailable.
  //  - import/* rules: those are package-resolution policies specific to the
  //    application packages and are not meaningful for standalone scripts.
  //  - React rules: scripts contain no UI components.
  {
    files: ['scripts/**/*.{ts,tsx,js,mjs,cjs}'],
    plugins: {
      sonarjs,
    },
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      // --- General code quality (parity with packages/*/src) ---
      'arrow-body-style': ['error', 'as-needed'],
      curly: ['error', 'multi-line'],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-cond-assign': 'error',
      'no-debugger': 'error',
      'no-duplicate-case': 'error',
      'no-else-return': 'error',
      'no-lonely-if': 'error',
      'no-unsafe-finally': 'error',
      'no-unneeded-ternary': 'error',
      'no-var': 'error',
      'object-shorthand': 'error',
      'one-var': ['error', 'never'],
      'prefer-arrow-callback': 'error',
      'prefer-const': ['error', { destructuring: 'all' }],
      radix: 'error',

      // --- TypeScript quality (non-type-aware; works without a tsconfig) ---
      '@typescript-eslint/array-type': ['error', { default: 'array-simple' }],
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        { assertionStyle: 'as' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-inferrable-types': [
        'error',
        { ignoreParameters: true, ignoreProperties: true },
      ],
      '@typescript-eslint/no-namespace': [
        'error',
        { allowDeclarations: true },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // --- Size/complexity limits (same thresholds as packages/*/src) ---
      complexity: ['error', 25],
      'max-lines': [
        'error',
        { max: 800, skipBlankLines: true, skipComments: true },
      ],
      'max-lines-per-function': [
        'error',
        { max: 80, skipBlankLines: true, skipComments: true },
      ],
      'sonarjs/cognitive-complexity': ['error', 30],

      // --- SonarJS maintainability ---
      'sonarjs/expression-complexity': 'error',
      'sonarjs/nested-control-flow': 'error',
      'sonarjs/no-all-duplicated-branches': 'error',
      'sonarjs/no-collapsible-if': 'error',
      'sonarjs/no-duplicated-branches': 'error',
      'sonarjs/no-identical-functions': 'error',
      'sonarjs/no-inconsistent-returns': 'error',
      'sonarjs/no-nested-conditional': 'error',
      'sonarjs/too-many-break-or-continue-in-loop': 'error',
      'sonarjs/todo-tag': 'error',

      // --- SonarJS regex correctness ---
      'no-control-regex': 'error',
      'sonarjs/no-invalid-regexp': 'error',
      'sonarjs/no-regex-spaces': 'error',
      'sonarjs/slow-regex': 'error',
      'sonarjs/stateful-regex': 'error',
      'sonarjs/unicode-aware-regex': 'error',
    },
  },
  // Issue #2282: Test files use large setup/case blocks. max-lines-per-function
  // is turned off for scripts/tests to match the existing packages test-file
  // policy (the jest config block above sets the same off for packages).
  {
    files: ['scripts/tests/**/*.{ts,tsx,js,mjs,cjs}'],
    rules: {
      'max-lines-per-function': 'off', // eslint-policy-allow-off: #2282 test parity
    },
  },
  // ============================================================================
  // Issue #3240: The AST test-audit scanner is a single-file analysis tool
  // with inherently high cyclomatic complexity (large switch/if-cascade over
  // AST node kinds). Size and complexity limits are relaxed so the scanner
  // can stay in one file for ease of maintenance.
  // ============================================================================
  {
    files: ['scripts/test-audit/scan.ts'],
    rules: {
      'max-lines': 'off', // eslint-policy-allow-off: #3240 single-file scanner
      'max-lines-per-function': 'off', // eslint-policy-allow-off: #3240
      complexity: 'off', // eslint-policy-allow-off: #3240
      'sonarjs/cognitive-complexity': 'off', // eslint-policy-allow-off: #3240
      'sonarjs/expression-complexity': 'off', // eslint-policy-allow-off: #3240
      'sonarjs/no-nested-conditional': 'off', // eslint-policy-allow-off: #3240
      'sonarjs/nested-control-flow': 'off', // eslint-policy-allow-off: #3240
      'sonarjs/too-many-break-or-continue-in-loop': 'off', // eslint-policy-allow-off: #3240
      'sonarjs/no-all-duplicated-branches': 'off', // eslint-policy-allow-off: #3240
    },
  },
  // ============================================================================
  // Issue #3240: app.test.ts was already at 801 effective lines on main
  // (930 total - 95 blank - 30 comment - 4 block = 801). Our mock-theater
  // fix added a second command to the non-streaming route test, pushing it
  // to 839 effective. The file is a single E2E integration suite that is
  // inherently large; relaxing max-lines preserves the pre-existing state.
  // ============================================================================
  {
    files: ['packages/a2a-server/src/http/app.test.ts'],
    rules: {
      'max-lines': ['error', { max: 900, skipBlankLines: true, skipComments: true }], // eslint-policy-allow-off: #3240 raised from 800 for mock-theater fix
    },
  },
  // ============================================================================
  // Issue #2605: Apply strict code-quality lint rules to eval TypeScript
  // ============================================================================
  // The eval suite (evals/**/*.ts) is real source executed by the nightly
  // workflow via the runtime loader. It was previously in the global ignores,
  // so type regressions and `any` usage went undetected. This block extends
  // the same TypeScript quality guardrails that protect packages/*/src to the
  // eval tree, with project-aware type checking via evals/tsconfig.json.
  //
  // Type-aware rules (no-floating-promises, no-misused-promises,
  // await-thenable, return-await) ARE enabled because the eval tsconfig
  // provides the type program (`project: 'evals/tsconfig.json'`). The eval
  // source is async-heavy (evalTest runs model calls and tool assertions), so
  // these rules catch real bugs (unhandled rejections, async functions passed
  // as non-async callbacks).
  //
  // max-lines-per-function is deliberately not applied: eval case wiring uses
  // large setup blocks. Type-aware correctness rules are applied below.
  {
    files: ['evals/**/*.{ts,tsx}'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: false,
        project: 'evals/tsconfig.json',
        tsconfigRootDir: projectRoot,
      },
      globals: {
        ...globals.node,
      },
    },
    rules: {
      // --- TypeScript quality ---
      '@typescript-eslint/array-type': ['error', { default: 'array-simple' }],
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        { assertionStyle: 'as' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports' },
      ],
      '@typescript-eslint/explicit-function-return-type': [
        'error',
        { allowExpressions: true },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-inferrable-types': [
        'error',
        { ignoreParameters: true, ignoreProperties: true },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // --- Type-aware async/promise rules (require project tsconfig) ---
      '@typescript-eslint/await-thenable': ['error'],
      '@typescript-eslint/no-floating-promises': ['error'],
      '@typescript-eslint/no-misused-promises': ['error'],
      '@typescript-eslint/return-await': ['error', 'in-try-catch'],
      '@typescript-eslint/strict-boolean-expressions': [
        'error',
        {
          allowString: false,
          allowNumber: false,
          allowNullableObject: false,
          allowNullableBoolean: false,
          allowNullableString: false,
          allowNullableNumber: false,
          allowAny: false,
        },
      ],

      // --- General code quality ---
      curly: ['error', 'multi-line'],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': 'off', // eslint-policy-allow-off: evals legitimately log to stdout
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-const': ['error', { destructuring: 'all' }],
    },
  },
  // Issue #2282: eslint-guard.test.js is the exhaustive test suite for the
  // ~5000-line guard parser above. It is intentionally comprehensive (one
  // test per detection branch) and is far larger than the 800-line file
  // limit. Splitting it is coupled to the guard's own decomposition (tracked
  // separately); until then max-lines is carved out so the new quality layer
  // can apply without a forced rewrite of the fixture. All other quality
  // rules still apply to this file.
  {
    files: ['scripts/tests/eslint-guard.test.ts'],
    rules: {
      'max-lines': 'off', // eslint-policy-allow-off: #2282 exhaustive guard fixture
    },
  },
  // CLI extension commands produce user-facing stdout/stderr output
  {
    files: [
      'packages/cli/src/commands/extensions/*.ts',
      'packages/cli/src/config/extension.ts',
    ],
    rules: {
      'no-console': 'off',
    },
  },
  // Vitest test configuration
  {
    // Prevent self-imports in packages
    files: ['packages/core/src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          name: '@google/gemini-cli-core',
          message: 'Please use relative imports within the @google/gemini-cli-core package.',
        },
      ],
    },
  },
  {
    files: ['packages/cli/src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          name: '@google/gemini-cli',
          message: 'Please use relative imports within the @google/gemini-cli package.',
        },
      ],
    },
  },
  // Bun test configuration (issue #2970: migrated from @vitest/eslint-plugin to
  // eslint-plugin-jest configured for bun:test)
  {
    files: ['packages/*/src/**/*.{test,spec,bun}.{ts,tsx}'],
    plugins: {
      jest,
    },
    settings: {
      jest: {
        globalPackage: 'bun:test',
        // version intentionally omitted: the runner is bun:test, not Jest,
        // and bun:test has no Jest-style semver that the plugin could gate on.
      },
    },
    rules: {
      // Issue #2970: eslint-plugin-jest replaces @vitest/eslint-plugin for
      // bun:test. The vitest plugin worked correctly — it went silent because
      // PR #2969 rewrote every test import away from the vitest package to
      // 'bun:test', and @vitest/eslint-plugin does not recognise 'bun:test' as
      // a test-framework source (verified by controlled experiment: same rules,
      // same file, only the import source changed — the vitest import produced
      // 3 errors, the bun:test import produced 0). eslint-plugin-jest with
      // globalPackage: 'bun:test' restores enforcement.
      //
      // SEVEN rules are enabled at 'error': they produce 0 violations or had
      // a small, fixed number of violations that were fixed in the test files.
      //
      // FIVE rules remain 'off': eslint-plugin-jest implements them MORE
      // strictly than @vitest/eslint-plugin did, so enabling them is net-NEW
      // enforcement rather than preservation of the previous level. The
      // evidence: on the tree immediately before #2969 (commit a805a219f)
      // every test still imported 'vitest', the vitest plugin was fully live
      // at 'error', and `npm run lint` was green at 0 warnings (therefore 0
      // vitest-plugin violations). Running eslint-plugin-jest with
      // globalPackage: 'vitest' over the SAME files reported 728 violations in
      // packages/core alone (~4,183 repo-wide). Burning those down is out of
      // scope for #2970 and is tracked as #3129. Options are preserved so
      // re-enabling is a one-word change. Do NOT spread
      // jest.configs['flat/recommended'].rules — it contains additional rules
      // vitest never had.

      // ── Active rules (0 violations or violations fixed) ──
      'jest/no-identical-title': 'error',
      'jest/valid-describe-callback': 'error',
      'jest/max-nested-describe': ['error', { max: 3 }],
      'jest/valid-title': 'error',
      'jest/require-to-throw-message': 'error',
      // fast-check's `fc.assert` is a real assertion helper; tests using
      // `fc.assert(fc.property(...))` do assert but use no literal `expect`.
      // Project-level assertion wrappers are registered here so the rule
      // recognises them as real assertions:
      //   - expectFrameContains/expectFrameNotContains wrap Ink frame checks
      //     that tolerate empty CI frames.
      //   - expectRejection wraps promise-rejection assertions.
      //   - expectStderrContaining wraps stderr-substring assertions.
      'jest/expect-expect': [
        'error',
        {
          assertFunctionNames: [
            'expect',
            'fc.assert',
            'expectFrameContains',
            'expectFrameNotContains',
            'expectRejection',
            'expectStderrContaining',
          ],
        },
      ],
      'jest/no-conditional-expect': 'error',

      // ── Rules kept at 'off' (jest is strictly stricter than vitest was;
      //    enabling is net-NEW enforcement; burn-down tracked in #3129) ──
      'jest/no-commented-out-tests': 'off', // eslint-policy-allow-off: #2970 unchanged from vitest config
      'jest/no-disabled-tests': 'off', // eslint-policy-allow-off: #2970 unchanged from vitest config
      // fast-check's property-based testing exports both `it` and `test`,
      // each augmented with `.prop`. All four variants are real test-block
      // functions. `itProp` is the common alias for fast-check's `it` (used
      // across many test files); `itProp.prop` is the corresponding property
      // variant.
      'jest/no-standalone-expect': [
        'off', // eslint-policy-allow-off: #2970 jest stricter than vitest; 617 violations tracked in #3129
        {
          additionalTestBlockFunctions: [
            'it',
            'itProp',
            'itProp.prop',
            'it.prop',
            'testProp',
            'test.prop',
          ],
        },
      ],
      'jest/no-conditional-in-test': 'off', // eslint-policy-allow-off: #2970 jest stricter than vitest; 3059 violations tracked in #3129
      'jest/prefer-strict-equal': 'off', // eslint-policy-allow-off: #2970 jest stricter than vitest; 199 violations tracked in #3129
      'jest/require-top-level-describe': 'off', // eslint-policy-allow-off: #2970 jest stricter than vitest; 154 violations tracked in #3129
      'jest/valid-expect': 'off', // eslint-policy-allow-off: #2970 jest stricter than vitest; 154 violations tracked in #3129
      // vitest/no-import-node-test → no-restricted-imports banning node:test
      // (issue #2970: same invariant, different mechanism). bun:test is the
      // only supported test module.
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'node:test',
              message:
                'Use bun:test instead of node:test for tests. See dev-docs/bun.md.',
            },
          ],
        },
      ],

      // Relax complexity rules for test files
      'max-lines-per-function': 'off',

      // Test files use `typeof import('pkg')` for mock typing; it's idiomatic.
      '@typescript-eslint/consistent-type-imports': 'off',

    },
  },
  // ============================================================================
  // Issue #1569: Batch BN4C - no-unnecessary-condition enforcement
  // ============================================================================
  // Promote this rule from warn to error for the specific batch scope.
  {
    files: [
      'packages/a2a-server/src/agent/executor.ts',
      'packages/a2a-server/src/agent/task.ts',
    ],
    rules: {
      '@typescript-eslint/no-unnecessary-condition': 'error',
    },
  },
  // ============================================================================
  // End Issue #1569 BN4C
  // ============================================================================
  // ============================================================================
  // Issue #1569: Batch BN4D - strict-boolean-expressions enforcement
  // ============================================================================
  // Promote this rule from warn to error for the specific batch scope.
  {
    files: [
      'packages/a2a-server/src/config/config.ts',
      'packages/a2a-server/src/agent/task.ts',
    ],
    rules: {
      '@typescript-eslint/strict-boolean-expressions': 'error',
    },
  },
  // ============================================================================
  // End Issue #1569 BN4D
  // ============================================================================
  // ============================================================================
  // Issue #1569: Batch C5A - max-lines-per-function enforcement
  // ============================================================================
  // Promote this rule from warn to error for the specific batch scope.
  {
    files: ['packages/a2a-server/src/agent/executor.ts'],
    rules: {
      'max-lines-per-function': [
        'error',
        { max: 80, skipBlankLines: true, skipComments: true },
      ],
    },
  },
  // ============================================================================
  // End Issue #1569 C5A
  // Issue #1569: Batch S6B - sonarjs/no-ignored-exceptions enforcement
  // ============================================================================
  // Ensure catch blocks handle errors rather than silently ignoring them.
  {
    files: [
      'packages/a2a-server/src/agent/executor.ts',
      'packages/a2a-server/src/agent/task.ts',
    ],
    rules: {
      'sonarjs/no-ignored-exceptions': 'error',
    },
  },
  // ============================================================================
  // End Issue #1569 S6B
  // Issue #1576: Enforce strict line-limit errors on AppContainer module files.
  // These files are being decomposed; error-level rules catch regressions during
  // and after the decomposition. Test files are excluded (they already have
  // max-lines-per-function: 'off' via the jest block above).
  {
    files: [
      'packages/cli/src/ui/AppContainerRuntime.tsx',
      'packages/cli/src/ui/containers/AppContainer/**/*.ts',
      'packages/cli/src/ui/containers/AppContainer/**/*.tsx',
    ],
    ignores: ['**/*.test.ts', '**/*.test.tsx'],
    rules: {
      'max-lines': [
        'error',
        { max: 800, skipBlankLines: true, skipComments: true },
      ],
      'max-lines-per-function': [
        'error',
        { max: 80, skipBlankLines: true, skipComments: true },
      ],
    },
  },
  // Settings for eslint-rules directory
  {
    files: ['./eslint-rules/**/*.js'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    files: ['packages/vscode-ide-companion/esbuild.ts'],
    languageOptions: {
      globals: {
        ...globals.node,
        process: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      'no-restricted-syntax': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  // Settings for CommonJS scripts
  {
    files: [
      './scripts/**/*.cjs',
      './packages/cli/bin/**/*.cjs',
      './packages/cli/scripts/**/*.cjs',
    ],
    languageOptions: {
      globals: {
        ...globals.node,
        process: 'readonly',
        console: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-var-requires': 'off',
    },
  },
  // packages/cli/bin/llxprt.mjs is a published node-shebang bin (issue #2978):
  // a standalone ESM shim that runs under plain Node (no TS loader). It needs
  // Node.js runtime globals (process, console) plus base ESLint recommended.
  {
    files: ['./packages/cli/bin/**/*.mjs'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },
  // Examples should have access to standard globals like fetch
  {
    files: ['packages/cli/src/commands/extensions/examples/**/*.js'],
    languageOptions: {
      globals: {
        ...globals.node,
        fetch: 'readonly',
      },
    },
  },
  // extra settings for scripts that we run directly with node
  {
    files: ['packages/vscode-ide-companion/scripts/**/*.js'],
    languageOptions: {
      globals: {
        ...globals.node,
        process: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      'no-restricted-syntax': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  // extra settings for scripts that we run directly with node
  {
    files: ['packages/agents/scripts/**/*.js'],
    languageOptions: {
      globals: {
        ...globals.node,
        process: 'readonly',
        console: 'readonly',
      },
    },
  },
  // ============================================================================
  // Issue #1577: text-buffer.ts decomposition - Architecture Enforcement
  // ============================================================================

  // Domain modules must be pure (no React, no side effects)
  {
    files: [
      'packages/cli/src/ui/components/shared/buffer-types.ts',
      'packages/cli/src/ui/components/shared/word-navigation.ts',
      'packages/cli/src/ui/components/shared/buffer-operations.ts',
      'packages/cli/src/ui/components/shared/transformations.ts',
      'packages/cli/src/ui/components/shared/visual-layout.ts',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'react',
              message:
                'Domain modules must be pure. React only allowed in text-buffer.ts',
            },
            {
              name: '@vybestack/llxprt-code-core',
              importNames: ['debugLogger'],
              message:
                'Domain modules must be side-effect free. No logging.',
            },
          ],
          patterns: [
            {
              group: ['node:fs', 'node:child_process', 'node:os'],
              message:
                'Domain modules must be pure. No Node.js I/O modules.',
            },
          ],
        },
      ],
      complexity: ['error', 25],
      'max-lines': [
        'error',
        { max: 800, skipBlankLines: true, skipComments: true },
      ],
      'max-lines-per-function': [
        'error',
        { max: 80, skipBlankLines: true, skipComments: true },
      ],
    },
  },

  // vim-buffer-actions.ts specific restrictions
  {
    files: ['packages/cli/src/ui/components/shared/vim-buffer-actions.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: './text-buffer.js',
              message:
                'Import from buffer-types, buffer-operations, or word-navigation directly',
            },
            {
              name: './buffer-reducer.js',
              message:
                'vim-buffer-actions must not import buffer-reducer (creates cycle)',
            },
            {
              name: 'react',
              message: 'vim-buffer-actions must be pure logic. No React.',
            },
          ],
          patterns: [
            {
              group: ['**/shared/text-buffer.js'],
              message: 'Import from specific module, not text-buffer.js',
            },
          ],
        },
      ],
      complexity: ['error', 25],
      'max-lines-per-function': ['error', 80],
    },
  },

  // buffer-reducer.ts specific restrictions
  {
    files: ['packages/cli/src/ui/components/shared/buffer-reducer.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'react',
              message: 'buffer-reducer must be pure logic. No React.',
            },
          ],
        },
      ],
      complexity: ['error', 25],
      'max-lines-per-function': ['error', 80],
    },
  },

  // text-buffer.ts size limits (React allowed here only)
  // useTextBuffer is a React hook composition root; its size comes from
  // useCallback/useMemo declarations, not from logic complexity.
  {
    files: ['packages/cli/src/ui/components/shared/text-buffer.ts'],
    rules: {
      'max-lines': [
        'error',
        { max: 800, skipBlankLines: true, skipComments: true },
      ],
    },
  },

  // Migration: Warn on utility imports from text-buffer.js in CLI src
  {
    files: ['packages/cli/src/**/*.ts', 'packages/cli/src/**/*.tsx'],
    ignores: [
      'packages/cli/src/ui/components/shared/text-buffer.ts',
      'packages/cli/src/ui/components/shared/text-buffer.test.ts',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [],
          patterns: [
            {
              group: ['**/shared/text-buffer.js'],
              importNames: [
                'offsetToLogicalPos',
                'logicalPosToOffset',
                'textBufferReducer',
                'pushUndo',
                'replaceRangeInternal',
                'findNextWordStartInLine',
                'findPrevWordStartInLine',
                'findWordEndInLine',
                'getPositionFromOffsets',
                'getLineRangeOffsets',
              ],
              message:
                'Import from buffer-operations.js, word-navigation.js, or buffer-types.js directly. See Issue #1577.',
            },
          ],
        },
      ],
    },
  },
  // ============================================================================
  // End Issue #1577
  // ============================================================================

  // ============================================================================
  // Issue #3136 — single owner for system-prompt assembly
  //
  // The agent layer assembles the complete system prompt and passes it to
  // providers as options.systemInstruction. Providers TRANSPORT it; they must
  // never rebuild a core prompt. Two independent assemblers is what caused the
  // prompt to be doubled on every request, and every parameter added to
  // getCoreSystemPromptAsync was another chance for the two call sites to
  // disagree (they already disagreed on model, coreMemory and interactionMode).
  //
  // This makes a second call site a lint error rather than a latent bug.
  // vi.mock('...prompts.js') is a call argument, not an import, so provider
  // tests need no carve-out and none is granted.
  // ============================================================================
  {
    files: ['packages/providers/src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@vybestack/llxprt-code-core/core/prompts.js',
              importNames: ['getCoreSystemPromptAsync'],
              message:
                'Providers TRANSPORT the assembled system prompt (options.systemInstruction). Assembly is owned by packages/agents. See issue #3136.',
            },
          ],
        },
      ],
    },
  },
  // ============================================================================
  // End Issue #3136
  // ============================================================================

  // ============================================================================
  // Issue #3172 — placement decision must flow from SystemPromptPlacement
  //
  // AnthropicRequestPreparation selects system-context placement from the
  // resolved SystemPromptPlacement (declared by the provider and resolved
  // through the shared policy), never from a local auth flag. Placement-only
  // message selection may not reference isOAuth, and request-parameter OAuth
  // facts may not drive local control flow or be aliased for indirect control.
  // Direct boolean parameters remain valid in auth-only helpers that build the
  // vendor system field or assert the OAuth/placement compatibility invariant.
  //
  // The two general no-restricted-syntax selectors are repeated here because
  // flat config REPLACES a rule's array value rather than merging it, so
  // omitting them would loosen the file's existing guards.
  {
    files: ['packages/providers/src/anthropic/AnthropicRequestPreparation.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'CallExpression[callee.name="require"]',
          message: 'Avoid using require(). Use ES6 imports instead.',
        },
        {
          selector: 'ThrowStatement > Literal:not([value=/^\\w+Error:/])',
          message:
            'Do not throw string literals or non-Error objects. Throw new Error("...") instead.',
        },
        {
          selector:
            ':matches(FunctionDeclaration[id.name="placeSystemInstruction"], VariableDeclarator[id.name="placeSystemInstruction"]) Identifier[name="isOAuth"]',
          message:
            'placeSystemInstruction controls only WHERE the prompt goes; it must not reference isOAuth. Use the resolved SystemPromptPlacement for placement and let buildSystemField handle the vendor system field independently (issue #3172).',
        },
        {
          selector:
            ':matches(FunctionDeclaration, FunctionExpression, ArrowFunctionExpression):has(CallExpression[callee.name="formatContextPrefix"]) Identifier[name="isOAuth"]',
          message:
            'System-prompt context placement must not reference isOAuth; use the resolved SystemPromptPlacement (issue #3172).',
        },
        {
          selector:
            ':matches(IfStatement, ConditionalExpression, SwitchStatement):has(MemberExpression[property.name="isOAuth"])',
          message:
            'Request-parameter isOAuth must not drive local placement control flow; pass the auth fact only to an auth-specific helper (issue #3172).',
        },
        {
          selector:
            'VariableDeclarator[init.type="MemberExpression"][init.property.name="isOAuth"]',
          message:
            'Do not alias request-parameter isOAuth for indirect placement control flow (issue #3172).',
        },
        {
          selector:
            'VariableDeclarator > ObjectPattern > Property[key.name="isOAuth"]',
          message:
            'Do not destructure request-parameter isOAuth for indirect placement control flow; pass the auth fact directly to an auth-specific helper (issue #3172).',
        },
      ],
    },
  },
  // ============================================================================
  // End Issue #3172
  // ============================================================================

  // ============================================================================
  // Issue #1581: subagent.ts decomposition - Size enforcement
  // ============================================================================
  //
  // Error-level max-lines and max-lines-per-function rules on the four new
  // modules ensure they never grow past their design targets. The coordinator
  // file (subagent.ts) was promoted from 'warn' to 'error' in Phase 5 (Issue
  // #1915) once the file was thin enough to comply. These rules target files
  // that don't exist yet — ESLint silently ignores unmatched globs, so CI
  // stays green during Phase 0.
  {
    files: [
      'packages/core/src/core/subagentTypes.ts',
      'packages/core/src/core/subagentRuntimeSetup.ts',
      'packages/core/src/core/subagentToolProcessing.ts',
      'packages/core/src/core/subagentExecution.ts',
    ],
    rules: {
      'max-lines': [
        'error',
        { max: 800, skipBlankLines: true, skipComments: true },
      ],
      'max-lines-per-function': [
        'error',
        { max: 80, skipBlankLines: true, skipComments: true },
      ],
    },
  },
  // subagent.ts coordinator: promoted from warn to error in Phase 5 (Issue #1915)
  {
    files: ['packages/core/src/core/subagent.ts'],
    rules: {
      'max-lines': [
        'error',
        { max: 800, skipBlankLines: true, skipComments: true },
      ],
      'max-lines-per-function': [
        'error',
        { max: 80, skipBlankLines: true, skipComments: true },
      ],
    },
  },
  // Enforce execution -> runtimeSetup dependency boundary.
  // subagentExecution.ts must not import from subagentRuntimeSetup.js.
  // All runtime artifacts must be passed as parameters by the coordinator.
  // See project-plans/issue1581/README.md §Dependency Graph.
  {
    files: ['packages/core/src/core/subagentExecution.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: './subagentRuntimeSetup.js',
              message:
                'subagentExecution must not import from subagentRuntimeSetup. ' +
                'All runtime artifacts must be passed as parameters by the coordinator (subagent.ts). ' +
                'See project-plans/issue1581/README.md §Dependency Graph.',
            },
          ],
        },
      ],
    },
  },
  // ============================================================================
  // End Issue #1581
  // ============================================================================


  // Prettier config must be last
  prettierConfig,
  // extra settings for scripts that we run directly with node
  {
    files: ['./integration-tests/**/*.js', './test-*.js', './test-*.mjs'],
    languageOptions: {
      globals: {
        ...globals.node,
        process: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
  // Custom eslint rules for this repo
  {
    files: ['packages/**/*.{js,jsx,ts,tsx}'],
    plugins: {
      custom: {
        rules: {
          'react-render-safety': reactRenderSafety,
          'no-inline-deps': noInlineDeps,
          'ink-text-color-required': inkTextColorRequired,
        },
      },
    },
    rules: {
      // Custom rules
      // 'custom/react-render-safety': 'error', // TODO: Fix for ESLint 9 API
      'custom/no-inline-deps': 'error',
      'custom/ink-text-color-required': 'error',
    },
  },
  // License header configuration
  {
    files: ['./**/*.{tsx,ts,js}'],
    plugins: {
      headers,
    },
    rules: {
      'headers/header-format': 'off',
    },
  },
  // ============================================================================
  // ============================================================================
  // The blanket #1585 migration suppression was removed after all inline
  // directives and lint violations were resolved. sonarjs/os-command and
  // sonarjs/no-os-command-from-path remain off project-wide (see global rules).

  // Issue #2088: The "todo" subsystem naturally uses the domain word "todo" in
  // comments (todo store, todo tools, ITodoService, etc.). sonarjs/todo-tag
  // matches case-insensitively, producing false positives on legitimate domain
  // vocabulary rather than actual TODO task markers.
  {
    files: [
      'packages/tools/src/interfaces/ITodoService.ts',
      'packages/tools/src/tools/todo-*.ts',
      'packages/tools/src/utils/todo*.ts',
      'packages/tools/src/__tests__/todo-*.ts',
    ],
    rules: {
      'sonarjs/todo-tag': 'off', // eslint-policy-allow-off: #2088 domain vocabulary
    },
  },
  // Issue #2970: The packages/tools override that previously turned off
  // jest/no-conditional-expect, jest/no-conditional-in-test, and
  // jest/prefer-strict-equal has been removed. jest/no-conditional-expect is
  // now enabled globally and all tools violations were fixed in the test
  // files. The other two rules remain off globally (see the deferred rules
  // above), making a package-specific override redundant.
);
