#!/bin/bash
# Test script for Phase 08b - Token Tracking Implementation

echo "Testing Phase 08b - Token Tracking for OpenAI Provider"
echo "======================================================"
echo ""
echo "This script tests token tracking and context percentage display"
echo ""
echo "Prerequisites:"
echo "1. Build the project: npm run build"
echo "2. Have an OpenAI API key configured"
echo ""
echo "Test sequence:"
echo "1. Start gemini-cli"
echo "2. Switch to OpenAI provider: /provider openai"
echo "3. Set API key if needed: /key sk-your-api-key"
echo "4. Send multiple messages to see context usage increase"
echo "5. Watch the status bar for context percentage updates"
echo ""
echo "Expected results:"
echo "- Context percentage should decrease as conversation progresses"
echo "- Usage data should be logged in console with '[OpenAIProvider] Usage data received:'"
echo "- Token counts should be accurate based on OpenAI's response"
echo ""
echo "To run in debug mode and see usage logs:"
echo "DEBUG=* npm run cli"