import { forbidHistoryMaterializationForTest } from '@vybestack/llxprt-code-test-utils/core/history-materialization-test-guard.js';
import { observeHistorySynchronouslyForTest as testHistory } from '@vybestack/llxprt-code-test-utils/core/synchronous-history-test-observation.js';
import { collectRowsForAssertions as withRows } from '@vybestack/llxprt-code-test-utils/core/collect-rows-for-assertions.js';
import { withCuratedHistoryForTest } from '@vybestack/llxprt-code-test-utils/core/curated-history-fixture.js';
/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Behavioral tests for model-origin stamping at the generation-recording
 * boundary (issue #2335).
 *
 * Stamping must happen ONLY where an AI turn that was JUST generated by the
 * model is converted to IContent and recorded — never on imported/restored/
 * rebuilt history. These tests build a real ConversationManager on top of a
 * real HistoryService and a real AgentRuntimeContext (no mock theater) and
 * assert that:
 *  - freshly generated model turns get metadata.model === the generating model,
 *  - user turns do NOT get stamped, and
 *  - imported/restored history does NOT get stamped.
 */

import { describe, it, expect, beforeEach, vi } from 'bun:test';
import { readFileSync } from 'node:fs';
import type { IContent } from '@vybestack/llxprt-code-core/services/history/IContent.js';
import { Config } from '@vybestack/llxprt-code-core/config/config.js';
import { SettingsService } from '@vybestack/llxprt-code-settings';
import {
  createProviderRuntimeContext,
  type ProviderRuntimeContext,
} from '@vybestack/llxprt-code-core/runtime/providerRuntimeContext.js';
import { createAgentRuntimeState } from '@vybestack/llxprt-code-core/runtime/AgentRuntimeState.js';
import { createAgentRuntimeContext } from '@vybestack/llxprt-code-core/runtime/createAgentRuntimeContext.js';
import { HistoryService } from '@vybestack/llxprt-code-core/services/history/HistoryService.js';
import {
  createProviderAdapterFromManager,
  createTelemetryAdapterFromConfig,
  createToolRegistryViewFromRegistry,
} from '@vybestack/llxprt-code-core/runtime/runtimeAdapters.js';
import { ConversationManager } from './ConversationManager.js';
import { TestRuntimeProviderManager } from '../test-utils/runtimeProviderManager.js';
import type { RuntimeProvider as IProvider } from '@vybestack/llxprt-code-core/runtime/contracts/RuntimeProvider.js';
import { createConfigParams } from './chatSession-runtime-helpers.js';

const GENERATING_MODEL = 'claude-opus-4-8';
const GENERATING_BASE_URL = 'https://api.anthropic.com';

function buildConversationManager(
  model: string,
  baseURL?: string,
): {
  conversationManager: ConversationManager;
  historyService: HistoryService;
} {
  const settingsService = new SettingsService();
  const config = new Config(createConfigParams(settingsService));

  settingsService.set('providers.stub.base-url', 'https://stub.example.com');
  settingsService.set('providers.stub.auth-key', 'stub-api-key');
  settingsService.set('providers.stub.model', 'stub-model');

  const providerRuntime: ProviderRuntimeContext = createProviderRuntimeContext({
    settingsService,
    config,
    runtimeId: 'test.runtime.conversationManager.modelStamp',
    metadata: { source: 'ConversationManager.modelStamp.test' },
  });

  const manager = new TestRuntimeProviderManager(providerRuntime);
  manager.setConfig(config);
  config.setProviderManager(manager);

  const provider: IProvider = {
    name: 'stub',
    isDefault: true,
    getModels: vi.fn(async () => []),
    getDefaultModel: () => model,
    generateChatCompletion: vi.fn(async function* () {}),
    getAuthToken: vi.fn(async () => 'stub-auth-token'),
  };
  manager.registerProvider(provider);

  const runtimeState = createAgentRuntimeState({
    runtimeId: 'runtime-conversationManager-modelStamp',
    provider: provider.name,
    model,
    sessionId: config.getSessionId(),
  });
  const historyService = new HistoryService();
  const view = createAgentRuntimeContext({
    state: runtimeState,
    history: historyService,
    settings: {
      compressionThreshold: 0.8,
      contextLimit: 200000,
      preserveThreshold: 0.2,
      telemetry: { enabled: true, target: null },
      // Include thoughts so the recording path exercises the thought-block
      // attachment that the fix stamps.
      'reasoning.includeInContext': true,
    },
    provider: createProviderAdapterFromManager(config.getProviderManager()),
    telemetry: createTelemetryAdapterFromConfig(config),
    tools: createToolRegistryViewFromRegistry(config.getToolRegistry()),
    providerRuntime: { ...providerRuntime },
  });

  const conversationManager = new ConversationManager(
    historyService,
    view,
    baseURL,
  );

  return { conversationManager, historyService };
}

describe('ConversationManager stamps model origin at recording boundary (issue #2335)', () => {
  it('stamps metadata.model on a freshly generated AI turn', async () => {
    const { conversationManager, historyService } = buildConversationManager(
      GENERATING_MODEL,
      GENERATING_BASE_URL,
    );
    const userInput: IContent = {
      speaker: 'human',
      blocks: [{ type: 'text', text: 'Hello' }],
    };
    const modelOutput: IContent[] = [
      {
        speaker: 'ai',
        blocks: [{ type: 'text', text: 'Hi there.' }],
      },
    ];

    await conversationManager.recordHistory(userInput, modelOutput);

    await withRows(historyService.streamRawHistory(), (rows) => {
      const all = rows;
      const ai = all.find((c) => c.speaker === 'ai');
      const human = all.find((c) => c.speaker === 'human');

      expect(ai?.metadata?.model).toBe(GENERATING_MODEL);
      expect(ai?.metadata?.providerBaseURL).toBe(GENERATING_BASE_URL);
      expect(human?.metadata?.model).toBeUndefined();
    });
  });

  it('stamps metadata.model on an AI turn that carries a signed thinking block', async () => {
    const { conversationManager, historyService } = buildConversationManager(
      GENERATING_MODEL,
      GENERATING_BASE_URL,
    );
    const userInput: IContent = {
      speaker: 'human',
      blocks: [{ type: 'text', text: 'Think and answer' }],
    };
    const modelOutput: IContent[] = [
      {
        speaker: 'ai',
        blocks: [
          {
            type: 'thinking',
            thought: 'reasoning about the answer',
            signature: 'sig-A',
            sourceField: 'thinking',
          },
          { type: 'text', text: 'The answer is 42.' },
        ],
      },
    ];

    await conversationManager.recordHistory(userInput, modelOutput);

    await withRows(historyService.streamRawHistory(), (rows) => {
      const all = rows;
      const ai = all.find((c) => c.speaker === 'ai');
      const human = all.find((c) => c.speaker === 'human');

      expect(ai?.metadata?.model).toBe(GENERATING_MODEL);
      expect(ai?.metadata?.providerBaseURL).toBe(GENERATING_BASE_URL);
      expect(human?.metadata?.model).toBeUndefined();

      // The signed thinking block must still be present (stamping does not strip).
      expect(
        ai?.blocks.some(
          (b) => b.type === 'thinking' && b.signature === 'sig-A',
        ),
      ).toBe(true);
    });
  });
});

describe('ConversationManager AFC model stamps', () => {
  it('stamps metadata.model on AI turns mixed into automaticFunctionCallingHistory but not user turns', async () => {
    const { conversationManager, historyService } = buildConversationManager(
      GENERATING_MODEL,
      GENERATING_BASE_URL,
    );
    const userInput: IContent = {
      speaker: 'human',
      blocks: [{ type: 'text', text: 'Run the tool' }],
    };
    const modelOutput: IContent[] = [
      { speaker: 'ai', blocks: [{ type: 'text', text: 'Done.' }] },
    ];
    // AFC history mixes freshly generated model turns with user turns.
    const automaticFunctionCallingHistory: IContent[] = [
      {
        speaker: 'tool',
        blocks: [
          {
            type: 'tool_response',
            callId: 'get_weather',
            toolName: 'get_weather',
            result: { temperature: 72 },
          },
        ],
      },
      {
        speaker: 'ai',
        blocks: [
          {
            type: 'tool_call',
            id: 'get_weather',
            name: 'get_weather',
            parameters: { city: 'SF' },
          },
        ],
      },
    ];

    await conversationManager.recordHistory(
      userInput,
      modelOutput,
      automaticFunctionCallingHistory,
    );

    await withRows(historyService.streamRawHistory(), (rows) => {
      const all = rows;
      const aiTurns = all.filter((c) => c.speaker === 'ai');
      const humanTurns = all.filter((c) => c.speaker === 'human');

      // Every recorded AI turn — including the one carried by the AFC history —
      // is stamped with the generating model.
      expect(aiTurns.length).toBeGreaterThan(0);
      for (const ai of aiTurns) {
        expect(ai.metadata?.model).toBe(GENERATING_MODEL);
        expect(ai.metadata?.providerBaseURL).toBe(GENERATING_BASE_URL);
      }
      // User turns (including those mixed into the AFC history) are not stamped.
      for (const human of humanTurns) {
        expect(human.metadata?.model).toBeUndefined();
      }
    });
  });
});

describe('ConversationManager AFC curated prefix', () => {
  it('deduplicates AFC against curated rows without materializing curated history', async () => {
    const { conversationManager, historyService } = buildConversationManager(
      GENERATING_MODEL,
      GENERATING_BASE_URL,
    );
    const call: IContent = {
      speaker: 'ai',
      blocks: [
        { type: 'tool_call', id: 'call-1', name: 'tool', parameters: {} },
      ],
    };
    const reply: IContent = {
      speaker: 'tool',
      blocks: [
        {
          type: 'tool_response',
          callId: 'call-1',
          toolName: 'tool',
          result: 7,
        },
      ],
    };
    historyService.add(
      { speaker: 'ai', blocks: [{ type: 'text', text: '' }] },
      GENERATING_MODEL,
    );
    await historyService.addBatch(
      [
        { speaker: 'human', blocks: [{ type: 'text', text: 'question' }] },
        call,
      ],
      GENERATING_MODEL,
    );
    await withCuratedHistoryForTest(historyService, async (existing) => {
      const afc = [
        ...existing.map((row) => ({
          ...row,
          metadata: { turnId: 'provider' },
        })),
        reply,
      ];
      const restoreMaterialization = forbidHistoryMaterializationForTest(
        historyService,
        'eager curated history',
      );
      try {
        await conversationManager.recordHistory(
          {
            speaker: 'human',
            blocks: [{ type: 'text', text: 'ignored in AFC' }],
          },
          [],
          afc,
        );
      } finally {
        restoreMaterialization();
      }
    });
    await withRows(historyService.streamRawHistory(), (rows) => {
      const all = rows;
      expect(all).toHaveLength(4);
      expect(all[3].blocks).toStrictEqual(reply.blocks);
    });
  });

  it('uses the scalar query for turn AFC offsets without an eager curated read', () => {
    const source = readFileSync(
      new URL('./turnHistoryCommit.ts', import.meta.url),
      'utf8',
    );
    const body = source
      .split('async function afcHistoryEntries(')[1]
      ?.split('\n}')[0];
    expect(body).toContain('await historyService.countCuratedRows()');
    expect(body).not.toMatch(/getCurated\s*\(|materializeHistory\s*\(/);
  });
});

describe('ConversationManager import/restore paths do NOT stamp (issue #2335)', () => {
  let conversationManager: ConversationManager;
  let historyService: HistoryService;

  beforeEach(() => {
    ({ conversationManager, historyService } =
      buildConversationManager(GENERATING_MODEL));
  });

  it('importInitialHistory does NOT stamp metadata.model on imported AI turns', () => {
    const importedHistory: IContent[] = [
      { speaker: 'human', blocks: [{ type: 'text', text: 'old question' }] },
      {
        speaker: 'ai',
        blocks: [{ type: 'text', text: 'old answer from a different model' }],
      },
    ];

    conversationManager.importInitialHistory(importedHistory, GENERATING_MODEL);

    const all = testHistory(historyService);
    const ai = all.find((c) => c.speaker === 'ai');

    // Imported turns have unknown origin and must remain unstamped.
    expect(ai?.metadata?.model).toBeUndefined();
    expect(ai?.metadata?.providerBaseURL).toBeUndefined();
  });

  it('setHistory does NOT stamp metadata.model on restored AI turns', async () => {
    const restoredHistory: IContent[] = [
      {
        speaker: 'human',
        blocks: [{ type: 'text', text: 'restored question' }],
      },
      { speaker: 'ai', blocks: [{ type: 'text', text: 'restored answer' }] },
    ];

    await conversationManager.setHistory(restoredHistory);

    await withRows(historyService.streamRawHistory(), (rows) => {
      const all = rows;
      const ai = all.find((c) => c.speaker === 'ai');

      expect(ai?.metadata?.model).toBeUndefined();
      expect(ai?.metadata?.providerBaseURL).toBeUndefined();
    });
  });

  it('addHistory does NOT stamp metadata.model on externally-supplied turns', () => {
    const externalAiTurn: IContent = {
      speaker: 'ai',
      blocks: [{ type: 'text', text: 'externally supplied model turn' }],
    };

    conversationManager.addHistory(externalAiTurn);

    const all = testHistory(historyService);
    const ai = all.find((c) => c.speaker === 'ai');

    expect(ai?.metadata?.model).toBeUndefined();
    expect(ai?.metadata?.providerBaseURL).toBeUndefined();
  });
});
