/**
 * @license
 * Copyright 2025 Vybestack LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Exact allowlist data for the provider-agnostic naming architecture gate.
 * Extracted into a separate module so the test file stays under max-lines.
 *
 * ALL entries are generated from a full workspace scan and correspond to
 * genuine Gemini references (provider, API key/model/env vars, @google/genai
 * wire-format concepts, .geminiignore/GEMINI.md paths, privacy notice,
 * content conversion, direct overrides, token extraction).
 */

/** Genuine Gemini provider/concept directory trees (root-relative prefix predicates). */
export const GENUINE_GEMINI_TREES: readonly string[] = [
  'providers/src/gemini/',
  'core/src/code_assist/',
  'core/src/prompt-config/defaults/providers/gemini/',
];

/** Exact genuine Gemini source files (not whole directories). */
export const GENUINE_GEMINI_FILES: readonly string[] = [
  'core/src/llm-types/geminiContent.ts',
  'core/src/llm-types/finishReasons.ts',
  'core/src/config/models.ts',
  'core/test/models/__fixtures__/mock-data.ts',
  'providers/src/auth/gemini-oauth-provider.ts',
  'providers/src/auth/gemini-oauth-provider.test.ts',
  'providers/src/ProviderManager.gemini-switch.test.ts',
  'providers/src/composition/provider-gemini-switching.test.ts',
];

/** Exact (relativePath, identifier) pairs for declared identifiers. */
export const ALLOWED_GEMINI_PAIRS: readonly string[] = [
  'core/src/core/contentGenerator.ts::geminiApiKey',
  'core/src/services/history/ContentConverters.ts::toGeminiContent',
  'core/src/services/history/ContentConverters.ts::toGeminiContents',
  'core/src/services/history/ContentConverters.test.ts::geminiContent',
  'core/src/services/history/ContentConverters.test.ts::geminiInput',
  'core/src/services/history/ContentConverters.test.ts::geminiContents',
  'core/src/services/history/ContentConverters.test.ts::gemini',
  'core/src/utils/filesearch/ignore.ts::geminiignorePath',
  'core/src/utils/memoryDiscovery.test.ts::projectRootGeminiFile',
  'core/src/utils/memoryDiscovery.test.ts::srcGeminiFile',
  'core/src/utils/memoryDiscovery.test.ts::subDirGeminiFile',
  'core/src/utils/memoryDiscovery.test.ts::cwdGeminiFile',
  'core/src/utils/memoryDiscovery.test.ts::rootGeminiFile',
  'core/src/utils/memoryDiscovery.test.ts::regularSubDirGeminiFile',
  'core/index.ts::DEFAULT_GEMINI_MODEL',
  'core/index.ts::DEFAULT_GEMINI_FLASH_MODEL',
  'core/index.ts::DEFAULT_GEMINI_FLASH_LITE_MODEL',
  'core/index.ts::DEFAULT_GEMINI_EMBEDDING_MODEL',
  'core/src/config/config.ts::DEFAULT_GEMINI_FLASH_MODEL',
  'core/src/config/index.ts::DEFAULT_GEMINI_FLASH_MODEL',
  'core/test/models/profiles.test.ts::geminiModel',
  'core/test/models/transformer.test.ts::geminiModel',
  'cli/src/config/providerModelResolver.ts::envGeminiModel',
  'cli/src/cli.test.tsx::originalEnvGeminiSandbox',
  'cli/src/ui/privacy/GeminiPrivacyNotice.tsx::GeminiPrivacyNoticeProps',
  'cli/src/ui/privacy/GeminiPrivacyNotice.tsx::GeminiPrivacyNotice',
  'cli/src/ui/components/ContextSummaryDisplay.tsx::geminiMdFileCount',
  'cli/src/ui/App.behavior.test.tsx::getAllGeminiMdFilenames',
  'cli/src/ui/App.components.test.tsx::getAllGeminiMdFilenames',
  'cli/src/ui/App.context.test.tsx::getAllGeminiMdFilenames',
  'cli/src/ui/App.dialogs.test.tsx::getAllGeminiMdFilenames',
  'cli/src/ui/App.test.tsx::getAllGeminiMdFilenames',
  'cli/src/integration-tests/__tests__/oauth-buckets.integration.spec.ts::geminiWork',
  'cli/src/integration-tests/__tests__/oauth-buckets.integration.spec.ts::geminiPersonal',
  'cli/src/integration-tests/__tests__/oauth-buckets.integration.spec.ts::geminiBuckets',
  'cli/src/integration-tests/__tests__/oauth-buckets.integration.spec.ts::geminiToken',
  'cli/src/integration-tests/__tests__/oauth-buckets.integration.spec.ts::geminiStillExists',
  'cli/src/integration-tests/provider-switching.integration.test.ts::geminiProvider',
  'cli/src/integration-tests/provider-switching.integration.test.ts::geminiSettings',
  'cli/src/providers/logging/multi-provider-logging.integration.test.ts::geminiProvider',
  'cli/src/providers/logging/multi-provider-logging.integration.test.ts::geminiWrapper',
  'cli/src/ui/oauth-submission.test.ts::geminiProvider',
  'cli/src/integration-tests/cli-args.profile-flag.integration.test.ts::expectGeminiProviderAttempt',
  'agents/src/core/DirectMessageProcessor.ts::_extractDirectGeminiOverrides',
  'auth/src/__tests__/auth-integration.spec.ts::mockGeminiProvider',
  'auth/src/__tests__/auth-integration.spec.ts::geminiEnabled',
  'auth/src/__tests__/auth-integration.spec.ts::geminiMetadata',
  'auth/src/__tests__/auth-integration.spec.ts::geminiAuth',
  'auth/src/__tests__/auth-integration.spec.ts::geminiStatus',
  'auth/src/__tests__/invalidateProviderCache.test.ts::geminiCallCount',
  'auth/src/__tests__/invalidateProviderCache.test.ts::geminiResolver',
  'auth/src/__tests__/invalidateProviderCache.test.ts::geminiToken1',
  'auth/src/__tests__/invalidateProviderCache.test.ts::geminiToken2',
  'auth/src/__tests__/token-store.spec.ts::_validGeminiToken',
  'auth/src/__tests__/token-store.spec.ts::geminiToken',
  'auth/src/__tests__/token-store.spec.ts::geminiBuckets',
  'telemetry/src/telemetry/events/session-events.ts::useGemini',
  'settings/src/profiles/__tests__/canonicalProfileRepair.testHelpers.ts::corruptCanonicalProfileNonGeminiModel',
  'settings/src/profiles/__tests__/canonicalProfileRepair.test.ts::corruptCanonicalProfileNonGeminiModel',
  'providers/src/composition/aliasProviderFactory.ts::createGeminiAliasProvider',
  'providers/src/composition/aliasProviderFactory.ts::GeminiProvider',
  'providers/src/composition/index.ts::createGeminiAliasProvider',
  'providers/src/index.ts::GeminiProvider',
  'providers/src/index.ts::buildGeminiDumpContents',
  'providers/src/utils/providerRequestConversion.ts::buildGeminiDumpContents',
  'providers/src/utils/providerRequestConversion.ts::isGeminiCompatibleProvider',
  'providers/src/utils/providerRequestConversion.ts::convertHistoryToGeminiFormat',
  'providers/src/logging/ProviderContentExtractor.ts::extractGeminiContent',
  'providers/src/logging/ProviderContentExtractor.ts::extractGeminiToolCalls',
  'providers/src/loadBalancing/backendMetrics.ts::extractGeminiTokens',
  'providers/src/loadBalancing/backendMetrics.ts::geminiTokens',
  'providers/src/ProviderManager.ts::geminiProvider',
  'providers/src/integration/multi-provider.integration.test.ts::savedGeminiKey',
  'providers/src/auth/oauth-manager.spec.ts::geminiProvider',
  'providers/src/auth/oauth-manager.spec.ts::geminiResult',
  'providers/src/auth/oauth-manager.spec.ts::geminiStatus',
  'providers/src/auth/__tests__/auth-status-service.spec.ts::geminiCoreProvider',
  'providers/src/auth/__tests__/OAuthBucketManager.spec.ts::geminiToken',
  'providers/src/auth/__tests__/OAuthBucketManager.spec.ts::geminiStatus',
  'providers/src/auth/proxy/__tests__/e2e-credential-flow.test.ts::geminiToken',
  'providers/src/auth/proxy/__tests__/refresh-coordinator.test.ts::geminiResult',
  'providers/src/auth/proxy/__tests__/refresh-flow.spec.ts::geminiProvider',
  'providers/src/auth/proxy/__tests__/refresh-flow.spec.ts::gemini',
  'providers/src/__tests__/LoadBalancingProvider.delegation.test.ts::mockGeminiProvider',
  'providers/src/__tests__/LoadBalancingProvider.delegation.test.ts::mockGemini',
  'providers/src/composition/providerManagerInstance.oauthRegistration.test.ts::MockGeminiProvider',
  'providers/src/composition/providerManagerInstance.schemaDefaults.test.ts::MockGeminiProvider',
];

/** Extended pairs discovered by the improved scanner (object-literal, type params). */
export const ALLOWED_GEMINI_PAIRS_EXTENDED: readonly string[] = [
  'agents/src/core/DirectMessageProcessor.ts::geminiDirectOverrides',
  'cli/src/utils/sandbox-containers.ts::GEMINI_API_KEY',
  'cli/src/utils/sandbox-containers.ts::GEMINI_MODEL',
  'cli/src/config/config.ts::envGeminiModel',
  'cli/src/config/__tests__/approvalModeParity.test.ts::respectGeminiIgnore',
  'cli/src/config/__tests__/e2eOrderingParity.test.ts::respectGeminiIgnore',
  'cli/src/config/__tests__/folderTrustOriginalSettingsParity.test.ts::respectGeminiIgnore',
  'cli/src/config/__tests__/mcpFilteringParity.test.ts::respectGeminiIgnore',
  'cli/src/config/__tests__/profileOverridePrecedenceParity.test.ts::respectGeminiIgnore',
  'cli/src/config/__tests__/providerModelPrecedenceParity.test.ts::respectGeminiIgnore',
  'cli/src/config/__tests__/toolGovernanceParity.test.ts::respectGeminiIgnore',
  'cli/src/config/config.part2.test.ts::respectGeminiIgnore',
  'cli/src/config/config.part3.test.ts::respectGeminiIgnore',
  'cli/src/config/config.part4.test.ts::respectGeminiIgnore',
  'cli/src/config/config.test.ts::respectGeminiIgnore',
  'cli/src/ui/components/SettingsDialog.interactions.test.tsx::respectGeminiIgnore',
  'cli/src/auth/oauth-settings-adapter.spec.ts::gemini',
  'cli/src/ui/components/AuthDialog.test.tsx::gemini',
  'cli/src/ui/components/ProfileCreateWizard/constants.ts::gemini',
  'cli/src/ui/components/WelcomeOnboarding/AuthMethodStep.tsx::gemini',
  'cli/src/ui/components/WelcomeOnboarding/ProviderSelectStep.tsx::gemini',
  'core/src/models/provider-integration.ts::gemini',
  'core/src/integration-tests/profile-integration.test.ts::gemini',
  'core/src/services/history/IContent.providerMetadata.test.ts::gemini',
  'core/src/utils/ignorePatterns.test.ts::getCurrentGeminiMdFilename',
  'providers/src/providerCapabilitiesService.ts::gemini',
  'providers/src/auth/__tests__/provider-registry.spec.ts::gemini',
  'providers/src/auth/file-oauth-settings.test.ts::gemini',
  'providers/src/composition/providerManagerInstance.oauthRegistration.test.ts::GeminiProvider',
  'providers/src/composition/providerManagerInstance.schemaDefaults.test.ts::GeminiProvider',
  'providers/src/runtime/provider-alias-defaults.modeldefaults.test.ts::gemini',
  'providers/src/runtime/provider-alias-defaults.propagation.test.ts::gemini',
  'providers/src/runtime/provider-alias-defaults.switch.test.ts::gemini',
];

/** Exact (relPath, moduleSpecifier, importedSymbol, localName) 4-tuples. */
export const ALLOWED_IMPORT_TUPLES: readonly string[] = [
  'a2a-server/src/config/config.ts::@vybestack/llxprt-code-core::DEFAULT_GEMINI_EMBEDDING_MODEL::DEFAULT_GEMINI_EMBEDDING_MODEL',
  'a2a-server/src/config/config.ts::@vybestack/llxprt-code-core::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler-test-helpers.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.agent-id.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.cancel-continuation.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.cancel-response.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.confirmation.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.context-aware.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.convert-response.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.edit-cancel.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.non-interactive.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.parallel.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.payload.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.policy.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.race-condition.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.suggest-edit.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.tool-suggestion.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.toolExecutor.characterization.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/coreToolScheduler.yolo.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/hookWireAdapter.ts::@vybestack/llxprt-code-core/llm-types/index.js::mapGeminiFinishReason::mapGeminiFinishReason',
  'agents/src/core/subagent-test-helpers.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/core/subagent.stream-idle.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'agents/src/scheduler/tool-dispatcher.test.ts::@vybestack/llxprt-code-core/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'cli/src/config/__tests__/providerModelPrecedenceParity.test.ts::@vybestack/llxprt-code-core::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'cli/src/config/providerModelResolver.ts::@vybestack/llxprt-code-core::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'cli/src/ui/hooks/usePromptCompletion.ts::@vybestack/llxprt-code-core::DEFAULT_GEMINI_FLASH_LITE_MODEL::DEFAULT_GEMINI_FLASH_LITE_MODEL',
  'cli/src/ui/privacy/PrivacyNotice.tsx::./GeminiPrivacyNotice.js::GeminiPrivacyNotice::GeminiPrivacyNotice',
  'core/src/config/__tests__/models.test.ts::../models.js::isGemini2Model::isGemini2Model',
  'core/src/config/__tests__/models.test.ts::../models.js::isGemini3Model::isGemini3Model',
  'core/src/config/config.ts::./models.js::DEFAULT_GEMINI_FLASH_MODEL::DEFAULT_GEMINI_FLASH_MODEL',
  'core/src/config/flashFallback.test.ts::./models.js::DEFAULT_GEMINI_FLASH_MODEL::DEFAULT_GEMINI_FLASH_MODEL',
  'core/src/config/flashFallback.test.ts::./models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'core/src/core/contentGenerator.ts::../config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'core/src/hooks/hookTranslator.ts::../config/models.js::DEFAULT_GEMINI_FLASH_MODEL::DEFAULT_GEMINI_FLASH_MODEL',
  'core/src/llm-types/finishReasons.test.ts::./finishReasons.js::GEMINI_FINISH_MAP::GEMINI_FINISH_MAP',
  'core/src/llm-types/finishReasons.test.ts::./finishReasons.js::mapGeminiFinishReason::mapGeminiFinishReason',
  'core/src/llm-types/modelEnvelope.ts::./finishReasons.js::GEMINI_FINISH_MAP::GEMINI_FINISH_MAP',
  'core/src/runtime/runtimeStateFactory.ts::../config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'core/src/services/history/ContentConverters.test.ts::../../llm-types/geminiContent.js::GeminiContent::GeminiContent',
  'core/src/services/history/ContentConverters.ts::../../llm-types/geminiContent.js::GeminiContent::GeminiContent',
  'core/src/services/history/ContentConverters.ts::../../llm-types/geminiContent.js::GeminiContentPart::GeminiContentPart',
  'core/src/utils/errorParsing.ts::../config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'core/src/utils/llm-edit-fixer.ts::../config/models.js::DEFAULT_GEMINI_FLASH_MODEL::DEFAULT_GEMINI_FLASH_MODEL',
  'core/src/utils/summarizer.ts::../config/models.js::DEFAULT_GEMINI_FLASH_LITE_MODEL::DEFAULT_GEMINI_FLASH_LITE_MODEL',
  'core/test/models/profiles.test.ts::./__fixtures__/mock-data.js::geminiModel::geminiModel',
  'core/test/models/transformer.test.ts::./__fixtures__/mock-data.js::geminiModel::geminiModel',
  'providers/src/fake/FakeProvider.ts::@vybestack/llxprt-code-core/llm-types/index.js::GeminiContent::GeminiContent',
  'providers/src/composition/aliasProviderFactory.ts::../gemini/GeminiProvider.js::GeminiProvider::GeminiProvider',
  'providers/src/utils/providerRequestConversion.ts::../gemini/GeminiMessageConverter.js::convertHistoryToGeminiFormat::convertHistoryToGeminiFormat',
  'settings/src/profiles/__tests__/canonicalProfileRepair.test.ts::./canonicalProfileRepair.testHelpers.js::corruptCanonicalProfileNonGeminiModel::corruptCanonicalProfileNonGeminiModel',
];

/** Exact (relPath, moduleSpecifier, originalSymbol, exportedName) 4-tuples. */
export const ALLOWED_EXPORT_TUPLES: readonly string[] = [
  'core/index.ts::./src/config/models.js::DEFAULT_GEMINI_MODEL::DEFAULT_GEMINI_MODEL',
  'core/index.ts::./src/config/models.js::DEFAULT_GEMINI_FLASH_MODEL::DEFAULT_GEMINI_FLASH_MODEL',
  'core/index.ts::./src/config/models.js::DEFAULT_GEMINI_FLASH_LITE_MODEL::DEFAULT_GEMINI_FLASH_LITE_MODEL',
  'core/index.ts::./src/config/models.js::DEFAULT_GEMINI_EMBEDDING_MODEL::DEFAULT_GEMINI_EMBEDDING_MODEL',
  'core/src/config/index.ts::./config.js::DEFAULT_GEMINI_FLASH_MODEL::DEFAULT_GEMINI_FLASH_MODEL',
  'core/src/config/index.ts::./models.js::DEFAULT_GEMINI_FLASH_MODEL::DEFAULT_FLASH_MODEL',
  'providers/src/composition/index.ts::./aliasProviderFactory.js::createGeminiAliasProvider::createGeminiAliasProvider',
  'providers/src/index.ts::./gemini/GeminiProvider.js::GeminiProvider::GeminiProvider',
  'providers/src/index.ts::./utils/providerRequestConversion.js::buildGeminiDumpContents::buildGeminiDumpContents',
];
