/**
 * @plan:PLAN-20260608-ISSUE1585.P10
 * @requirement:REQ-BEHAVIORAL-TDD, REQ-TEST-FIXTURE-COUPLING
 */

/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Provider Formatting / Tool ID Normalization Behavioral Tests
 *
 * Verifies that the formatter and normalization functions consumed by
 * providers produce output matching pre-extraction characterization fixtures.
 * These tests live in the providers package because that is where
 * ToolFormatter and normalization functions are consumed most heavily.
 *
 * Primary assertions: formatted output matches fixture byte-for-byte.
 * No mock theater — real formatter code with real fixture inputs.
 *
 * Provider mock exception: These tests import formatter code from
 * @vybestack/llxprt-code-tools (self-contained copy). No provider mocks
 * are used because the formatter is the code under test. Per mock hygiene
 * rules, this is the real formatter integration test path.
 */

import { describe, it, expect } from 'vitest';
import {
  ToolFormatter,
  normalizeToOpenAIToolId,
  normalizeToHistoryToolId,
  normalizeToAnthropicToolId,
  shouldUseDoubleEscapeHandling,
  detectDoubleEscaping,
  detectDoubleEscapingInChunk,
  processToolParameters,
} from '@vybestack/llxprt-code-tools';

import { TOOL_FORMATTER_FIXTURES } from './provider-formatting-fixtures.js';

// Dynamic fixture generation removed — fixture is now a static local file
// generated by the capture script with the same source as the tools package fixture.

describe('Provider Formatting Behavioral Tests @plan:PLAN-20260608-ISSUE1585.P10', () => {
  describe('ToolFormatter converts Gemini tools to Anthropic format', () => {
    it('matches pre-extraction fixture output byte-for-byte', () => {
      const formatter = new ToolFormatter();
      const fixture = TOOL_FORMATTER_FIXTURES.anthropicToolDeclaration;

      const geminiTools = [
        {
          functionDeclarations: [
            {
              name: 'read_file',
              description: 'Read the contents of a file',
              parametersJsonSchema: {
                type: 'object',
                properties: {
                  file_path: {
                    type: 'string',
                    description: 'Path to the file',
                  },
                  offset: { type: 'number', description: 'Line offset' },
                },
                required: ['file_path'],
              },
            },
            {
              name: 'write_file',
              description: 'Write content to a file',
              parametersJsonSchema: {
                type: 'object',
                properties: {
                  file_path: { type: 'string' },
                  content: { type: 'string' },
                },
                required: ['file_path', 'content'],
              },
            },
          ],
        },
      ];

      const result = formatter.convertGeminiToAnthropic(geminiTools);

      // Assert observable output matches fixture
      expect(result).toHaveLength(fixture.length);
      for (let i = 0; i < result.length; i++) {
        expect(result[i].name).toBe(fixture[i].name);
        expect(result[i].description).toBe(fixture[i].description);
        expect(result[i].input_schema.type).toBe(fixture[i].input_schema.type);
      }
    });
  });

  describe('ToolFormatter converts Gemini tools to OpenAI format', () => {
    it('matches pre-extraction fixture output byte-for-byte', () => {
      const formatter = new ToolFormatter();
      const fixture = TOOL_FORMATTER_FIXTURES.openAIToolDeclaration;

      const geminiTools = [
        {
          functionDeclarations: [
            {
              name: 'read_file',
              description: 'Read the contents of a file',
              parametersJsonSchema: {
                type: 'object',
                properties: {
                  file_path: {
                    type: 'string',
                    description: 'Path to the file',
                  },
                  offset: { type: 'number', description: 'Line offset' },
                },
                required: ['file_path'],
              },
            },
            {
              name: 'write_file',
              description: 'Write content to a file',
              parametersJsonSchema: {
                type: 'object',
                properties: {
                  file_path: { type: 'string' },
                  content: { type: 'string' },
                },
                required: ['file_path', 'content'],
              },
            },
          ],
        },
      ];

      const result = formatter.convertGeminiToOpenAI(geminiTools);

      expect(result).toHaveLength(fixture.length);
      for (let i = 0; i < result.length; i++) {
        expect(result[i].type).toBe(fixture[i].type);
        expect(result[i].function.name).toBe(fixture[i].function.name);
        expect(result[i].function.description).toBe(
          fixture[i].function.description,
        );
      }
    });
  });

  describe('Tool ID normalization', () => {
    it('normalizeToOpenAIToolId matches fixture for each test case', () => {
      for (const tc of TOOL_FORMATTER_FIXTURES.toolIdNormalizationCases) {
        expect(normalizeToOpenAIToolId(tc.input)).toBe(tc.openAI);
      }
    });

    it('normalizeToHistoryToolId matches fixture for each test case', () => {
      for (const tc of TOOL_FORMATTER_FIXTURES.toolIdNormalizationCases) {
        expect(normalizeToHistoryToolId(tc.input)).toBe(tc.history);
      }
    });

    it('normalizeToAnthropicToolId matches fixture for each test case', () => {
      for (const tc of TOOL_FORMATTER_FIXTURES.toolIdNormalizationCases) {
        expect(normalizeToAnthropicToolId(tc.input)).toBe(tc.anthropic);
      }
    });
  });

  describe('Double-escape handling', () => {
    it('shouldUseDoubleEscapeHandling returns correct value per format', () => {
      expect(shouldUseDoubleEscapeHandling('openai')).toBe(false);
      expect(shouldUseDoubleEscapeHandling('qwen')).toBe(true);
      expect(shouldUseDoubleEscapeHandling('anthropic')).toBe(false);
    });

    it('detectDoubleEscaping identifies simple JSON correctly', () => {
      const simpleCase = TOOL_FORMATTER_FIXTURES.doubleEscapeCases[0];
      const result = detectDoubleEscaping(simpleCase.input);
      expect(result.isDoubleEscaped).toBe(simpleCase.detection.isDoubleEscaped);
    });

    it('detectDoubleEscaping identifies double-escaped JSON correctly', () => {
      const doubleCase = TOOL_FORMATTER_FIXTURES.doubleEscapeCases[1];
      const result = detectDoubleEscaping(doubleCase.input);
      expect(result.isDoubleEscaped).toBe(doubleCase.detection.isDoubleEscaped);
    });

    it('detectDoubleEscapingInChunk detects escape patterns', () => {
      const simpleCase = TOOL_FORMATTER_FIXTURES.doubleEscapeCases[0];
      expect(detectDoubleEscapingInChunk(simpleCase.input)).toBe(
        simpleCase.detectedInChunk,
      );
    });

    it('processToolParameters produces correct output for fixture inputs', () => {
      const procCase = TOOL_FORMATTER_FIXTURES.doubleEscapeCases[2];
      if ('processed_openai' in procCase) {
        const resultOpenai = processToolParameters(
          procCase.input,
          'test_tool',
          'openai',
        );
        expect(resultOpenai).toEqual(procCase.processed_openai);
      }
      if ('processed_qwen' in procCase) {
        const resultQwen = processToolParameters(
          procCase.input,
          'test_tool',
          'qwen',
        );
        expect(resultQwen).toEqual(procCase.processed_qwen);
      }
    });
  });
});
