name: Bug Report
description: Report a bug to help us improve LLxprt Code
labels: ['kind/bug', 'status/need-triage']
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Thanks for taking the time to fill out this bug report!
        >
        > Please search **[existing issues](https://github.com/vybestack/llpxrt-code/issues)** to see if an issue already exists for the bug you encountered.

  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Client information
      description: |
        Run the `/about` command in LLxprt Code and paste the complete output below.
        Also include your platform (macOS/Windows/Linux).
      placeholder: |
        Paste the output from `/about` here...
    validations:
      required: true

  - type: textarea
    id: login-info
    attributes:
      label: Login information
      description: Describe how you are logging in (e.g., Google Account, API key).

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else we need to know?
      description: Add any other context about the problem here.
