/**
 * @license
 * Copyright 2025 Vybestack LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Build-boundary contract guard for the agents tsconfig providers path
 * mappings.
 *
 * The agents package imports several subpaths from
 * `@vybestack/llxprt-code-providers` (`composition.js`, `runtime.js`,
 * `auth.js`, plus the bare root). When the agents tsconfig does NOT map those
 * specifiers to providers source, TypeScript (and the isolated API-surface
 * declaration build in scripts/check-agents-api-surface.mjs) resolves them via
 * the node_modules symlink to `package.json` `exports.types`, which points at
 * `packages/providers/dist`. That dist is gitignored and only regenerated by an
 * explicit providers build, so on a fresh checkout — or whenever the committed
 * source gains a new option that stale dist lacks — the agents typecheck and
 * API-surface pretest fail with TS2353 against a phantom "missing" property.
 *
 * The cli package establishes the project convention: map each consumed
 * providers subpath to its source file. This test pins that same contract for
 * agents so the declaration/typecheck flow is source-bound and never depends on
 * a prebuilt (and potentially stale) providers dist.
 */

import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { describe, it, expect } from 'vitest';

interface ParsedTsConfig {
  compilerOptions?: {
    paths?: Record<string, string[]>;
  };
}

async function loadAgentsTsConfig(): Promise<ParsedTsConfig> {
  const configPath = resolve(
    fileURLToPath(new URL('../../..', import.meta.url)),
    'tsconfig.json',
  );
  let raw: string;
  try {
    raw = await readFile(configPath, 'utf8');
  } catch (error) {
    throw new Error(
      `Failed to read agents tsconfig at ${configPath}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  // The agents tsconfig is plain JSON (no comments) so a direct parse is safe
  // and avoids pulling a JSONC parser into the test. Wrap the parse so a
  // malformed config (e.g. during an active migration edit or bad merge)
  // surfaces a clear diagnostic instead of a raw syntax-error stack trace.
  try {
    return JSON.parse(raw) as ParsedTsConfig;
  } catch (error) {
    throw new Error(
      `Failed to parse agents tsconfig at ${configPath} as JSON: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

describe('agents tsconfig maps providers to source (build-boundary) @plan:issue2606', () => {
  it('maps the bare providers root to providers source index @requirement:source-bound-deps @given:the agents tsconfig paths @when:the providers root alias is inspected @then:it resolves to ../providers/index.ts (not dist)', async () => {
    const config = await loadAgentsTsConfig();
    const paths = config.compilerOptions?.paths;
    expect(paths).toBeDefined();
    expect(paths?.['@vybestack/llxprt-code-providers']).toStrictEqual([
      '../providers/index.ts',
    ]);
  });

  it('maps every providers subpath consumed by agents source to source (not dist) @requirement:source-bound-deps @given:the agents tsconfig paths @when:the composition/runtime/auth subpath aliases are inspected @then:each resolves into ../providers/src/**', async () => {
    const config = await loadAgentsTsConfig();
    const paths = config.compilerOptions?.paths;
    expect(paths).toBeDefined();

    // Verify exact one-to-one mapping for each subpath to prevent
    // misconfiguration where one subpath silently points at the wrong module.
    const expectedTargets: Record<string, string> = {
      '@vybestack/llxprt-code-providers/auth.js':
        '../providers/src/auth/index.ts',
      '@vybestack/llxprt-code-providers/composition.js':
        '../providers/src/composition/index.ts',
      '@vybestack/llxprt-code-providers/runtime.js':
        '../providers/src/runtime/index.ts',
    };
    for (const [subpath, expectedTarget] of Object.entries(expectedTargets)) {
      expect(
        paths?.[subpath]?.[0],
        `missing or incorrect path mapping for ${subpath}`,
      ).toBe(expectedTarget);
    }
  });

  it('provides a wildcard fallback so any future providers source import resolves to source @requirement:source-bound-deps @given:the agents tsconfig paths @when:the providers wildcard alias is inspected @then:it maps to ../providers/src/*', async () => {
    const config = await loadAgentsTsConfig();
    const paths = config.compilerOptions?.paths;
    expect(paths?.['@vybestack/llxprt-code-providers/*']).toStrictEqual([
      '../providers/src/*',
    ]);
  });
});
