/**
 * @license
 * Copyright 2025 Vybestack LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { spawnSync, type SpawnSyncReturns } from 'node:child_process';
import {
  accessSync,
  chmodSync,
  copyFileSync,
  constants,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { basename, dirname, join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  formatLauncher,
  outputMatches,
  runInWorkingDirectory,
} from '../generate-cli-launcher.js';

const repoRoot = resolve(import.meta.dirname, '../..');
const generatorPath = join(repoRoot, 'scripts', 'generate-cli-launcher.ts');
const canonicalSource = join(
  repoRoot,
  'packages',
  'cli',
  'src',
  'launcher',
  'cli-bin.cts',
);
const canonicalPolicy = join(
  dirname(canonicalSource),
  'bun-candidate-policy.ts',
);
const loadCommonJsModule = createRequire(import.meta.url);
const SPAWN_TIMEOUT_MS = 30_000;
const SPAWN_TEST_TIMEOUT_MS = SPAWN_TIMEOUT_MS + 10_000;
const DOUBLE_SPAWN_TEST_TIMEOUT_MS = SPAWN_TIMEOUT_MS * 2 + 10_000;

type TextSpawnResult = SpawnSyncReturns<'utf8'>;

interface CommonJsLauncher {
  readonly runCliBin: () => unknown;
}

function spawnDiagnostics(result: TextSpawnResult): string {
  return [
    `status: ${String(result.status)}`,
    `signal: ${String(result.signal)}`,
    `error: ${result.error?.message ?? '<none>'}`,
    `stdout: ${result.stdout}`,
    `stderr: ${result.stderr}`,
  ].join('\n');
}

function loadLauncher(output: string): CommonJsLauncher {
  const loaded: unknown = loadCommonJsModule(output);
  if (
    typeof loaded !== 'object' ||
    loaded === null ||
    !('runCliBin' in loaded) ||
    typeof loaded.runCliBin !== 'function'
  ) {
    throw new Error(
      `Generated launcher at ${output} does not export runCliBin`,
    );
  }
  return { runCliBin: loaded.runCliBin };
}

function executableExists(path: string): boolean {
  try {
    accessSync(path, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

function resolveRequiredBun(): string {
  const directCandidates = [
    process.env['BUN_PATH'],
    join(repoRoot, 'node_modules', 'bun', 'bin', 'bun.exe'),
    join(repoRoot, 'node_modules', 'bun', 'bin', 'bun'),
  ]
    .filter((candidate): candidate is string => candidate !== undefined)
    .map((candidate) => candidate.replace(/^(["'])(.+?)\1$/, '$2'));
  const direct = directCandidates.find(executableExists);
  if (direct !== undefined) {
    return direct;
  }

  const lookupTool = process.platform === 'win32' ? 'where.exe' : 'which';
  const lookup = spawnSync(lookupTool, ['bun'], {
    encoding: 'utf8',
    timeout: SPAWN_TIMEOUT_MS,
  });
  if (lookup.status === 0) {
    const fromPath = lookup.stdout
      .split(/\r?\n/)
      .map((candidate) => candidate.trim().replace(/^(["'])(.+?)\1$/, '$2'))
      .find((candidate) => candidate.length > 0 && executableExists(candidate));
    if (fromPath !== undefined) {
      return fromPath;
    }
  }

  throw new Error(
    `Bun is required for CLI launcher generator tests. Set BUN_PATH, install the repository bun dependency, or put bun on PATH. Lookup diagnostics: ${spawnDiagnostics(lookup)}`,
  );
}

let repositoryBun: string | undefined;

function getRepositoryBun(): string {
  repositoryBun ??= resolveRequiredBun();
  return repositoryBun;
}

function expectSpawnSuccess(result: TextSpawnResult): void {
  const diagnostics = spawnDiagnostics(result);
  expect(result.error, diagnostics).toBeUndefined();
  expect(result.status, diagnostics).toBe(0);
}

function runGenerator(args: readonly string[]): TextSpawnResult {
  return spawnSync(getRepositoryBun(), [generatorPath, ...args], {
    cwd: repoRoot,
    encoding: 'utf8',
    timeout: SPAWN_TIMEOUT_MS,
  });
}

function copyEquivalentLauncherSource(targetDir: string): string {
  mkdirSync(targetDir, { recursive: true });
  const source = join(targetDir, 'cli-bin.cts');
  copyFileSync(canonicalSource, source);
  copyFileSync(canonicalPolicy, join(targetDir, 'bun-candidate-policy.ts'));
  return source;
}

function expectGeneratedBytesExcludePath(bytes: string, path: string): void {
  const lowerBytes = bytes.toLowerCase();
  const backslashPath = path.replace(/\//g, '\\');
  const variants = new Set(
    [
      path,
      path.replace(/\\/g, '/'),
      backslashPath,
      backslashPath.replace(/\\/g, '\\\\'),
    ].map((variant) => variant.toLowerCase()),
  );
  for (const variant of variants) {
    expect(
      lowerBytes,
      `generated bytes should not contain path variant: ${variant}`,
    ).not.toContain(variant);
  }
}

describe('CLI launcher generation', () => {
  it('rejects direct Node invocation before parsing generator options', () => {
    const result = spawnSync(process.execPath, [generatorPath, '--source='], {
      cwd: repoRoot,
      encoding: 'utf8',
      timeout: SPAWN_TIMEOUT_MS,
    });
    const diagnostics = spawnDiagnostics(result);

    expect(result.error, diagnostics).toBeUndefined();
    expect(result.status, diagnostics).not.toBe(0);
    expect(result.stderr, diagnostics).toContain(
      'CLI launcher generation requires the Bun runtime',
    );
    expect(result.stderr, diagnostics).toContain(
      '`npm run generate:cli-launcher`',
    );
    expect(result.stderr, diagnostics).not.toContain(
      '--source requires a path',
    );
    expect(result.stderr, diagnostics).not.toContain(
      'Failed to build CLI launcher',
    );
  });

  it('rejects direct Node invocation when import.meta.main is unavailable', () => {
    const tempDir = mkdtempSync(
      join(dirname(generatorPath), '.cli-launcher-no-import-meta-main-'),
    );
    const copiedGenerator = join(tempDir, basename(generatorPath));

    try {
      const source = readFileSync(generatorPath, 'utf8');
      const sourceWithoutImportMetaMain = source.replace(
        /import\.meta\.main/g,
        'undefined',
      );
      expect(sourceWithoutImportMetaMain).not.toBe(source);
      writeFileSync(copiedGenerator, sourceWithoutImportMetaMain);

      const result = spawnSync(
        process.execPath,
        [copiedGenerator, '--source='],
        {
          cwd: repoRoot,
          encoding: 'utf8',
          timeout: SPAWN_TIMEOUT_MS,
        },
      );
      const diagnostics = spawnDiagnostics(result);

      expect(result.error, diagnostics).toBeUndefined();
      expect(result.status, diagnostics).not.toBe(0);
      expect(result.stderr, diagnostics).toContain(
        'CLI launcher generation requires the Bun runtime',
      );
      expect(result.stderr, diagnostics).not.toContain(
        '--source requires a path',
      );
    } finally {
      rmSync(tempDir, { recursive: true, force: true });
    }
  });

  it(
    'uses a quoted BUN_PATH candidate without falling back to the repository Bun',
    () => {
      const tempDir = mkdtempSync(join(tmpdir(), 'quoted-bun-path-'));
      const copiedBun = join(tempDir, basename(getRepositoryBun()));
      const originalBunPath = process.env['BUN_PATH'];

      try {
        copyFileSync(getRepositoryBun(), copiedBun);
        chmodSync(copiedBun, statSync(getRepositoryBun()).mode);
        process.env['BUN_PATH'] = `"${copiedBun}"`;

        expect(resolveRequiredBun()).toBe(copiedBun);
      } finally {
        if (originalBunPath === undefined) {
          delete process.env['BUN_PATH'];
        } else {
          process.env['BUN_PATH'] = originalBunPath;
        }
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    SPAWN_TEST_TIMEOUT_MS,
  );

  it('preserves a build failure while reporting a concurrent cwd restoration failure', async () => {
    const buildFailure = new Error('build failed');
    const restorationFailure = new Error('cwd restore failed');
    const reported: unknown[] = [];

    const result = runInWorkingDirectory(
      'source-directory',
      async () => {
        throw buildFailure;
      },
      {
        cwd: () => 'original-directory',
        chdir: (path) => {
          if (path === 'original-directory') {
            throw restorationFailure;
          }
        },
        reportRestorationFailure: (error) => reported.push(error),
      },
    );

    await expect(result).rejects.toBe(buildFailure);
    expect(reported).toStrictEqual([restorationFailure]);
  });

  it('surfaces cwd restoration failure when the build succeeds', async () => {
    const restorationFailure = new Error('cwd restore failed');

    const result = runInWorkingDirectory(
      'source-directory',
      async () => 'generated',
      {
        cwd: () => 'original-directory',
        chdir: (path) => {
          if (path === 'original-directory') {
            throw restorationFailure;
          }
        },
        reportRestorationFailure: () => {
          throw new Error('restoration failure should not be reported twice');
        },
      },
    );

    await expect(result).rejects.toBe(restorationFailure);
  });

  it('identifies source and output paths in formatting failure diagnostics', async () => {
    const source = join(repoRoot, 'source', 'cli-bin.cts');
    const output = join(repoRoot, 'output', 'llxprt.cjs');
    const formattingFailure = new Error('formatter failed');

    await expect(
      formatLauncher('module.exports = {};', source, output, async () => {
        throw formattingFailure;
      }),
    ).rejects.toThrowError(
      `Failed to format CLI launcher (source: ${source}, output: ${output}): formatter failed`,
    );
  });

  it(
    'creates a missing output parent directory',
    () => {
      const tempDir = mkdtempSync(join(tmpdir(), 'cli-launcher-parent-'));
      const output = join(tempDir, 'missing', 'nested', 'llxprt.cjs');

      try {
        const result = runGenerator(['--output', output]);

        expectSpawnSuccess(result);
        expect(readFileSync(output, 'utf8')).toMatch(/^#!\/usr\/bin\/env node/);
      } finally {
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    SPAWN_TEST_TIMEOUT_MS,
  );

  it(
    'uses the final repeated equals-separated source and output paths',
    () => {
      const tempDir = mkdtempSync(
        join(tmpdir(), 'cli-launcher-equals-source-'),
      );
      const source = copyEquivalentLauncherSource(join(tempDir, 'source'));
      const output = join(tempDir, 'output', 'llxprt.cjs');
      const sourceMarker = 'LLXPRT_EQUALS_SOURCE_OPTION';

      try {
        writeFileSync(
          source,
          readFileSync(source, 'utf8').replace(
            'LLXPRT_BUN_RELAUNCHED',
            sourceMarker,
          ),
        );
        const result = runGenerator([
          '--source=',
          `--source=${source}`,
          '--output=',
          `--output=${output}`,
        ]);

        expectSpawnSuccess(result);
        expect(readFileSync(output, 'utf8')).toContain(sourceMarker);
      } finally {
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    SPAWN_TEST_TIMEOUT_MS,
  );

  it.each([
    {
      earlierOption: '--source=ignored',
      finalOption: '--source=',
      diagnostic: '--source requires a path',
    },
    {
      earlierOption: '--output=ignored',
      finalOption: '--output=',
      diagnostic: '--output requires a path',
    },
  ])(
    'rejects the final empty equals-separated option $finalOption',
    ({ earlierOption, finalOption, diagnostic }) => {
      const result = runGenerator(['--check', earlierOption, finalOption]);
      const diagnostics = spawnDiagnostics(result);

      expect(result.status, diagnostics).not.toBe(0);
      expect(result.stderr, diagnostics).toContain(diagnostic);
    },
  );

  it(
    'identifies the target path when the generated launcher cannot be written',
    () => {
      const tempDir = mkdtempSync(join(tmpdir(), 'cli-launcher-write-error-'));

      try {
        const result = runGenerator(['--output', tempDir]);
        const diagnostics = spawnDiagnostics(result);

        expect(result.status, diagnostics).not.toBe(0);
        expect(result.stderr, diagnostics).toContain(
          `Failed to write CLI launcher to ${tempDir}`,
        );
      } finally {
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    SPAWN_TEST_TIMEOUT_MS,
  );

  it('treats only a missing output as stale during check', async () => {
    const tempDir = mkdtempSync(join(tmpdir(), 'cli-launcher-read-error-'));

    try {
      await expect(
        outputMatches(join(tempDir, 'missing.cjs'), 'generated'),
      ).resolves.toBe(false);
      await expect(outputMatches(tempDir, 'generated')).rejects.toMatchObject({
        code: expect.stringMatching(/^(EISDIR|EPERM)$/),
      });
    } finally {
      rmSync(tempDir, { recursive: true, force: true });
    }
  });

  it(
    'identifies source and output paths in build failure diagnostics',
    () => {
      const tempDir = mkdtempSync(join(tmpdir(), 'cli-launcher-diagnostic-'));
      const source = join(tempDir, 'invalid-launcher.cts');
      const output = join(tempDir, 'output', 'llxprt.cjs');

      try {
        writeFileSync(source, 'const invalid: =;\n');
        const result = runGenerator(['--source', source, '--output', output]);
        const diagnostics = spawnDiagnostics(result);

        expect(result.status, diagnostics).not.toBe(0);
        expect(result.stderr, diagnostics).toContain(source);
        expect(result.stderr, diagnostics).toContain(output);
      } finally {
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    SPAWN_TEST_TIMEOUT_MS,
  );

  it(
    'generates a Node-loadable CommonJS launcher with a shebang',
    () => {
      const tempDir = mkdtempSync(join(tmpdir(), 'cli-launcher-generate-'));
      const output = join(tempDir, 'llxprt.cjs');

      try {
        const result = runGenerator(['--output', output]);
        expectSpawnSuccess(result);
        const generated = readFileSync(output, 'utf8');
        expect(generated).toMatch(/^#!\/usr\/bin\/env node\r?\n/);
        expect(generated).toContain('Object.is(module, require.main)');
        expect(typeof loadLauncher(output).runCliBin).toBe('function');
      } finally {
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    SPAWN_TEST_TIMEOUT_MS,
  );

  it(
    'does not embed the repository absolute path in generated bytes',
    () => {
      const tempDir = mkdtempSync(join(tmpdir(), 'cli-launcher-portable-'));
      const output = join(tempDir, 'llxprt.cjs');

      try {
        const result = runGenerator(['--output', output]);
        expectSpawnSuccess(result);
        const generated = readFileSync(output, 'utf8');
        expectGeneratedBytesExcludePath(generated, repoRoot);
        expect(generated).toContain('runtimeModuleFilename(module)');
      } finally {
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    SPAWN_TEST_TIMEOUT_MS,
  );

  it(
    'produces byte-identical output from equivalent sources in different absolute directories',
    () => {
      const tempDir = mkdtempSync(join(tmpdir(), 'cli-launcher-determinism-'));
      const firstSource = copyEquivalentLauncherSource(
        join(tempDir, 'first-source'),
      );
      const secondSource = copyEquivalentLauncherSource(
        join(tempDir, 'second-source'),
      );
      const first = join(tempDir, 'first.cjs');
      const second = join(tempDir, 'second.cjs');

      try {
        const firstResult = runGenerator([
          '--source',
          firstSource,
          '--output',
          first,
        ]);
        const secondResult = runGenerator([
          '--source',
          secondSource,
          '--output',
          second,
        ]);
        expectSpawnSuccess(firstResult);
        expectSpawnSuccess(secondResult);
        expect(readFileSync(first)).toStrictEqual(readFileSync(second));
      } finally {
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    DOUBLE_SPAWN_TEST_TIMEOUT_MS,
  );

  it(
    'checks a synchronized generated launcher without rewriting it',
    () => {
      const tempDir = mkdtempSync(join(tmpdir(), 'cli-launcher-check-'));
      const output = join(tempDir, 'llxprt.cjs');

      try {
        const generation = runGenerator(['--output', output]);
        expectSpawnSuccess(generation);
        const before = readFileSync(output);
        const result = runGenerator(['--check', '--output', output]);

        expectSpawnSuccess(result);
        expect(readFileSync(output)).toStrictEqual(before);
      } finally {
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    DOUBLE_SPAWN_TEST_TIMEOUT_MS,
  );

  it(
    'rejects stale generated output with the regeneration command',
    () => {
      const tempDir = mkdtempSync(join(tmpdir(), 'cli-launcher-stale-'));
      const output = join(tempDir, 'llxprt.cjs');

      try {
        writeFileSync(output, '#!/usr/bin/env node\nstale\n');
        const result = runGenerator(['--check', '--output', output]);
        const diagnostics = spawnDiagnostics(result);

        expect(result.error, diagnostics).toBeUndefined();
        expect(result.status, diagnostics).not.toBe(0);
        expect(result.stderr, diagnostics).toContain(
          'npm run generate:cli-launcher',
        );
        expect(readFileSync(output, 'utf8')).toContain('stale');
      } finally {
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    SPAWN_TEST_TIMEOUT_MS,
  );

  it(
    'runs from a relocated package with its sibling entry and local native Bun',
    () => {
      const tempDir = mkdtempSync(join(tmpdir(), 'cli-launcher-relocated-'));
      const packageRoot = join(tempDir, 'installed-package');
      const launcher = join(packageRoot, 'bin', 'llxprt.cjs');
      const localBun = join(
        packageRoot,
        'node_modules',
        'bun',
        'bin',
        basename(getRepositoryBun()),
      );
      const emptyPath = join(tempDir, 'empty-path');

      try {
        mkdirSync(dirname(launcher), { recursive: true });
        mkdirSync(dirname(localBun), { recursive: true });
        mkdirSync(emptyPath, { recursive: true });
        copyFileSync(getRepositoryBun(), localBun);
        chmodSync(localBun, statSync(getRepositoryBun()).mode);
        writeFileSync(
          join(packageRoot, 'index.ts'),
          [
            'process.stdout.write([',
            '  process.execPath,',
            "  'relocated-sibling-entry',",
            '  ...process.argv.slice(2),',
            '].join("\\n"));',
          ].join('\n'),
        );

        const generation = runGenerator(['--output', launcher]);
        expectSpawnSuccess(generation);

        const result = spawnSync(
          process.execPath,
          [launcher, '--prompt', 'package local'],
          {
            cwd: tempDir,
            env: { ...process.env, PATH: emptyPath, Path: emptyPath },
            encoding: 'utf8',
            timeout: SPAWN_TIMEOUT_MS,
          },
        );
        expectSpawnSuccess(result);
        const [observedBun, ...observedOutput] = result.stdout
          .trim()
          .split(/\r?\n/);
        if (observedBun === undefined) {
          throw new Error(
            'relocated launcher did not report its Bun executable',
          );
        }
        expect(realpathSync(observedBun)).toBe(realpathSync(localBun));
        expect(observedOutput).toStrictEqual([
          'relocated-sibling-entry',
          '--prompt',
          'package local',
        ]);
      } finally {
        rmSync(tempDir, { recursive: true, force: true });
      }
    },
    DOUBLE_SPAWN_TEST_TIMEOUT_MS,
  );

  it(
    'keeps the checked-in launcher runnable before a project build',
    () => {
      const launcher = join(repoRoot, 'packages', 'cli', 'bin', 'llxprt.cjs');
      const result = spawnSync(process.execPath, [launcher, '--version'], {
        cwd: repoRoot,
        encoding: 'utf8',
        timeout: SPAWN_TIMEOUT_MS,
      });

      expectSpawnSuccess(result);
      expect(result.stdout.trim()).toMatch(/^\d+\.\d+\.\d+/);
    },
    SPAWN_TEST_TIMEOUT_MS,
  );
});
