/**
 * @license
 * Copyright 2026 Vybestack LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import type { BunTestWorkspaceEntry } from './bun-test-manifest.ts';

export const TOOLS_MANIFEST_ENTRY: BunTestWorkspaceEntry = {
  workspace: 'tools',
  preload: 'test-setup-storage-isolation.ts',
  files: [
    'test-bun/imageDimensions.bun.ts',
    'test-bun/imageTokenEstimation.bun.ts',
    'test-bun/language-analysis.followup.bun.ts',
    'test-bun/shell-wrapper.bun.ts',
    'test-bun/shell-tool-signal-format.bun.ts',
    'src/tools/activate-skill.test.ts',
    'src/tools/ast-edit.ide.test.ts',
    'src/tools/edit-utils.test.ts',
    'src/tools/exa-web-search.test.ts',
    'src/tools/direct-web-fetch.test.ts',
    'src/tools/github.test.ts',
    'src/tools/github-ops.test.ts',
    'src/tools/github-display.test.ts',
    'src/tools/github-unknown-param.bun.test.ts',
    'src/tools/line-range-tools-issue3036.bun.test.ts',
    'src/tools/check-async-tasks.test.ts',
    'src/tools/list-subagents.test.ts',
    'src/tools/codesearch.test.ts',
    'src/tools/codesearch-endpoint.bun.test.ts',
    'src/tools/structural-analysis/structural-analysis-modes.bun.test.ts',
    'src/tools/memoryTool.test.ts',
    'src/tools/write-file.test.ts',
    'src/tools/tools.test.ts',
    'src/tools/todo-store-injection.test.ts',
    'src/tools/todo-store-single-resolve.test.ts',
    'src/tools/generate-image/GenerateImageTool.test.ts',
    'src/tools/generate-image/GenerateImageTool.surface.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-issue-1756.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-issue-3035.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-issue-3035-review.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-summary-counts.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-rust-validation.test.ts',
    'src/tools/ast-edit/__tests__/validation-categorizer.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-ast-validation.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-preview.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-concurrency.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-edge-cases.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-preview-gaps.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-ambiguous-match.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-force-flag.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-crlf.test.ts',
    'src/tools/ast-edit/__tests__/ast-edit-c-validation.test.ts',
    'src/tools/ast-edit/__tests__/language-analysis.test.ts',
    'src/formatters/ToolFormatter.test.ts',
    'src/formatters/toolGovernanceUtils.test.ts',
    'src/formatters/doubleEscapeUtils.test.ts',
    'src/utils/ast-grep-utils.lazy.import-effects.test.ts',
    'src/utils/ast-grep-utils.lazy.registration.test.ts',
    'src/utils/ast-grep-utils.lazy.parsesource-registration.test.ts',
    'src/utils/ast-grep-utils.lazy.degradation.test.ts',
    'src/utils/ast-grep-utils.lazy.available-before-registration.test.ts',
    'src/utils/ast-grep-utils.lazy.import-throws.test.ts',
    'src/utils/imageResize.test.ts',
    'src/utils/timeoutResolution.test.ts',
    'src/utils/fileUtils.test.ts',
    'src/utils/textDelta.test.ts',
    'src/__tests__/shell-tool.test.ts',
    'src/__tests__/shell-timeout-bounds.test.ts',
    'src/__tests__/edit-ast-tools.test.ts',
    'src/__tests__/public-surface.task-tool.test.ts',
    'src/__tests__/removed-google-tools.test.ts',
    'src/__tests__/interface-contracts.test.ts',
    'src/__tests__/read-many-files-filtering-behavior.test.ts',
    'src/__tests__/tool-registry-mcp-lazy.test.ts',
    'src/__tests__/registry-contract.test.ts',
    'src/__tests__/forbidden-dependencies.test.ts',
    'src/__tests__/package-boundary.test.ts',
    'src/__tests__/shell-helpers-schema.test.ts',
    'src/__tests__/tool-key-storage.test.ts',
    'src/__tests__/glob-filtering-behavior.test.ts',
    'src/__tests__/todo-tools.test.ts',
    'src/__tests__/export-surface-helpers.test.ts',
    'src/__tests__/apply-patch.test.ts',
    'src/__tests__/apply-patch-ax.bun.test.ts',
    'src/__tests__/glob-filtering.test.ts',
    'src/__tests__/ls-filtering-behavior.test.ts',
    'src/__tests__/neutral-types.test.ts',
    'src/__tests__/package-metadata.test.ts',
    'src/__tests__/filesystem-tools.test.ts',
    // Issue #3063: ReadFileTool.execute() must keep both halves of its error.
    'src/tools/__tests__/read-file-direct-api.test.ts',
    'src/__tests__/boundary-scan.test.ts',
    'src/__tests__/ripGrep-args.test.ts',
    'src/__tests__/wire-types.test.ts',
    'src/__tests__/forbidden-imports.test.ts',
    'src/__tests__/memory-tool.test.ts',
    'src/__tests__/todo-emoji-filter.test.ts',
    'src/__tests__/subagent-tools.test.ts',
  ],
};
