#!/usr/bin/env bun
/**
 * @license
 * Copyright 2025 Vybestack LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * genai-import-inventory.ts
 *
 * Generates a deterministic inventory of every tracked TypeScript file under
 * `packages/**` that imports `@google/genai`, classifying each importer to the
 * downstream issue that owns its migration (#2348 / #2349 / #2350 / #2351) or
 * to the permanent Gemini `enclave`.
 *
 * This is the baseline that the #2352 enforcement ratchet compares against:
 * the inventory may only ever SHRINK as migration issues land. The
 * `--check` mode regenerates the table in memory and diffs it against the
 * checked-in baseline file (`dev-docs/genai-import-baseline.md`); any drift
 * (a new importer, a removed importer, or a reclassification) exits non-zero.
 *
 * Classification uses path-prefix rules only (first match wins) — no per-file
 * hardcoded lists — so the script stays maintainable as files move.
 *
 * Usage:
 *   scripts/genai-import-inventory.ts            # write the baseline file
 *   scripts/genai-import-inventory.ts --check    # diff against baseline
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// ─── Types ──────────────────────────────────────────────────────────────────

export type Classification =
  | { kind: 'issue'; issue: string }
  | { kind: 'enclave' }
  | { kind: 'error'; error: string };

export interface InventoryEntry {
  readonly file: string;
  readonly owner: string;
}

/**
 * A path-prefix → owner classification rule. See PREFIX_RULES for the
 * first-match-wins ordering.
 */
interface PrefixRule {
  readonly prefix: string;
  readonly owner: string;
}

// ─── Constants ──────────────────────────────────────────────────────────────

/**
 * Prefix rules in first-match-wins order. Each entry maps a path prefix to the
 * owning issue (or `enclave`). A path that matches NO rule is an error: the
 * script exits 1 listing the offending path so every importer is consciously
 * classified.
 *
 * Rule order matters: more specific enclaves (gemini, code_assist) must come
 * before the broader package rules they nest inside (providers, core).
 */
const PREFIX_RULES: readonly PrefixRule[] = [
  // ── Permanent Gemini enclaves ──────────────────────────────────────────
  // These two subtrees are the ONLY locations permitted to import
  // @google/genai once #2352 completes. They are the end-state enclaves.
  { prefix: 'packages/providers/src/gemini/', owner: 'enclave' },
  { prefix: 'packages/core/src/code_assist/', owner: 'enclave' },

  // ── Migration-issue-owned packages ─────────────────────────────────────
  { prefix: 'packages/core/', owner: '#2348' },
  { prefix: 'packages/agents/', owner: '#2349' },
  { prefix: 'packages/cli/', owner: '#2350' },

  // Leaf packages: tools, mcp, telemetry, a2a-server, test-utils.
  { prefix: 'packages/tools/', owner: '#2351' },
  { prefix: 'packages/mcp/', owner: '#2351' },
  { prefix: 'packages/telemetry/', owner: '#2351' },
  { prefix: 'packages/a2a-server/', owner: '#2351' },
  { prefix: 'packages/test-utils/', owner: '#2351' },

  // ── Providers non-gemini remainder ─────────────────────────────────────
  // Shared provider-layer files and non-Gemini provider implementations
  // that still reference Google types. Owned by #2349 (provider-layer
  // shared files).
  { prefix: 'packages/providers/', owner: '#2349' },

  // NOTE: anything else is intentionally unmatched → error.
];

/**
 * Matches a quoted `@google/genai` module specifier — covers import, export,
 * require, dynamic-import, and subpath imports like `'@google/genai/foo'`.
 * The surrounding quotes ensure unquoted prose comments (e.g.
 * "no @google/genai import") are NOT matched.
 */
const GENAI_IMPORT_PATTERN = /['"`]@google\/genai['"`]|['"`]@google\/genai\//;

/**
 * Pure content-matching predicate: returns true when `content` contains a
 * quoted `@google/genai` module specifier. Exported so the matcher logic can
 * be unit-tested without touching the filesystem.
 */
export function isGenaiImporterContent(content: string): boolean {
  return GENAI_IMPORT_PATTERN.test(content);
}
const BASELINE_RELATIVE_PATH = 'dev-docs/genai-import-baseline.md';
const GENERATED_BY_NOTE =
  '<!-- GENERATED by scripts/genai-import-inventory.ts — do not edit by hand. ' +
  'This is the #2352 enforcement ratchet baseline. ' +
  'Run `scripts/genai-import-inventory.ts` to regenerate. -->';

// ─── Repo-root resolution ───────────────────────────────────────────────────

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Deterministic code-unit comparison for stable sorting across environments.
 * Uses raw `<`/`>` (not `localeCompare`) so output is identical regardless of
 * the host's LC_COLLATE setting.
 */
function compareStrings(a: string, b: string): number {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
}

// ─── Classification (pure, unit-tested) ─────────────────────────────────────

/**
 * Classify a single tracked file path to its owning issue or enclave.
 *
 * Returns `{ kind: 'issue', issue }` on a match, `{ kind: 'enclave' }` for
 * permanent Gemini enclaves, or `{ kind: 'error', error }` when the path
 * matches no prefix rule. The first matching rule wins; rule order is defined
 * by PREFIX_RULES (enclaves before the broader package rules they nest inside).
 *
 * This function is pure (no I/O, no globals beyond the constant rule table)
 * so it can be unit-tested directly without touching the filesystem.
 */
export function classifyGenaiImporter(path: string): Classification {
  for (const rule of PREFIX_RULES) {
    if (path.startsWith(rule.prefix)) {
      if (rule.owner === 'enclave') {
        return { kind: 'enclave' };
      }
      return { kind: 'issue', issue: rule.owner };
    }
  }
  return {
    kind: 'error',
    error:
      `unmatched path '${path}' — no classification rule matches. ` +
      'Add a prefix rule or rehome the file into a classified package.',
  };
}

// ─── File discovery ─────────────────────────────────────────────────────────

/**
 * Return the sorted list of tracked `.ts`/`.tsx` files under `packages/**`
 * whose content contains an `@google/genai` import specifier.
 *
 * Uses `git ls-files` for the tracked-file list (deterministic, ignores
 * node_modules/dist/build) and a content scan for the import filter.
 */
function findGenaiImporters(): string[] {
  let tracked: string;
  try {
    tracked = execFileSync(
      'git',
      ['ls-files', 'packages/**/*.ts', 'packages/**/*.tsx'],
      {
        cwd: REPO_ROOT,
        encoding: 'utf8',
        maxBuffer: 64 * 1024 * 1024,
      },
    );
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error(
      `genai-import-inventory: git ls-files failed (is git on PATH ` +
        `and is this a git repo?): ${msg}`,
    );
    process.exit(1);
  }
  const files = tracked
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

  const importers: string[] = [];
  for (const relPath of files) {
    const absPath = join(REPO_ROOT, relPath);
    let content: string;
    try {
      content = readFileSync(absPath, 'utf8');
    } catch (e) {
      // A tracked file that cannot be read is a hard error: silently skipping
      // could hide a lost importer and cause a false baseline match in --check
      // mode.
      const msg = e instanceof Error ? e.message : String(e);
      console.error(
        `genai-import-inventory: could not read tracked file '${relPath}': ${msg}`,
      );
      process.exit(1);
    }
    if (isGenaiImporterContent(content)) {
      importers.push(relPath);
    }
  }
  importers.sort();
  return importers;
}

// ─── Inventory + rendering ──────────────────────────────────────────────────

interface InventoryResult {
  readonly entries: readonly InventoryEntry[];
  readonly errors: readonly string[];
}

/**
 * Build the classified inventory. Returns the sorted entries plus any
 * classification errors (unmatched paths). Callers must treat a non-empty
 * `errors` list as a hard failure.
 */
function buildInventory(files: readonly string[]): InventoryResult {
  const entries: InventoryEntry[] = [];
  const errors: string[] = [];
  for (const file of files) {
    const classification = classifyGenaiImporter(file);
    if (classification.kind === 'error') {
      errors.push(classification.error);
      continue;
    }
    entries.push({
      file,
      owner:
        classification.kind === 'enclave' ? 'enclave' : classification.issue,
    });
  }
  // Stable sort by file path (the input is already sorted, but keep it
  // explicit so rendering is deterministic regardless of input order).
  // Code-unit comparison (not localeCompare) for fully deterministic output
  // across environments with different LC_COLLATE settings.
  entries.sort((a, b) => compareStrings(a.file, b.file));
  return { entries, errors };
}

/**
 * Render the inventory as a deterministic markdown document.
 *
 * Layout:
 *   - generated-by header comment
 *   - total count + per-owner breakdown
 *   - the file | owner table, sorted by file path
 */
function renderInventory(result: InventoryResult): string {
  const total = result.entries.length;
  const perOwner = new Map<string, number>();
  for (const entry of result.entries) {
    perOwner.set(entry.owner, (perOwner.get(entry.owner) ?? 0) + 1);
  }

  const lines: string[] = [];
  lines.push(GENERATED_BY_NOTE);
  lines.push('');
  lines.push('# `@google/genai` Import Inventory Baseline');
  lines.push('');
  lines.push(
    'Every tracked TypeScript file under `packages/**` that imports ' +
      '`@google/genai`, classified to the downstream issue that removes the ' +
      'import (or to the permanent Gemini `enclave`). This file is the ' +
      'baseline the #2352 enforcement ratchet compares against — the count ' +
      'may only ever decrease as migration issues land.',
  );
  lines.push('');
  lines.push(`**Total importers:** ${total}`);
  lines.push('');
  lines.push('**Per-owner breakdown:**');
  lines.push('');

  // Deterministic owner order: enclave first, then issue numbers ascending.
  // Code-unit comparison (not localeCompare) for cross-environment determinism.
  const ownerOrder = Array.from(perOwner.keys()).sort((a, b) => {
    if (a === 'enclave') return -1;
    if (b === 'enclave') return 1;
    return compareStrings(a, b);
  });
  for (const owner of ownerOrder) {
    lines.push(`- \`${owner}\`: ${perOwner.get(owner) ?? 0}`);
  }
  lines.push('');

  lines.push(renderOwnerTable(result.entries));
  lines.push('');
  return lines.join('\n');
}

/**
 * Render the file→owner table with column widths matching what Prettier's
 * Markdown formatter produces, so the generated baseline is stable under
 * `npm run format` (Prettier left-pads each cell to the column's max content
 * width). Column width = max length of any cell's display text (excluding the
 * surrounding `| ` / ` ` padding, which is applied uniformly).
 */
function renderOwnerTable(entries: readonly InventoryEntry[]): string {
  const fileHeader = 'File';
  const ownerHeader = 'Owner';
  const rows: ReadonlyArray<{ readonly file: string; readonly owner: string }> =
    [
      { file: fileHeader, owner: ownerHeader },
      ...entries.map((e) => ({
        file: '`' + e.file + '`',
        owner: e.owner,
      })),
    ];
  const fileWidth = Math.max(...rows.map((r) => r.file.length));
  const ownerWidth = Math.max(...rows.map((r) => r.owner.length));

  const lines: string[] = [];
  // Header
  lines.push(
    '| ' +
      rows[0].file.padEnd(fileWidth) +
      ' | ' +
      rows[0].owner.padEnd(ownerWidth) +
      ' |',
  );
  // Separator (dashes fill the column width, accounting for the surrounding spaces)
  lines.push(
    '| ' + '-'.repeat(fileWidth) + ' | ' + '-'.repeat(ownerWidth) + ' |',
  );
  // Data rows
  for (const row of rows.slice(1)) {
    lines.push(
      '| ' +
        row.file.padEnd(fileWidth) +
        ' | ' +
        row.owner.padEnd(ownerWidth) +
        ' |',
    );
  }
  return lines.join('\n');
}

// ─── Main ───────────────────────────────────────────────────────────────────

function main(): void {
  const args = process.argv.slice(2);
  const checkOnly = args.includes('--check');

  const files = findGenaiImporters();
  const result = buildInventory(files);

  if (result.errors.length > 0) {
    console.error(
      `genai-import-inventory: ${result.errors.length} unclassified ` +
        'importer(s) — every @google/genai importer must match a prefix rule:',
    );
    for (const err of result.errors) {
      console.error('  ' + err);
    }
    process.exit(1);
  }

  const generated = renderInventory(result);
  const baselinePath = join(REPO_ROOT, BASELINE_RELATIVE_PATH);

  if (checkOnly) {
    if (!existsSync(baselinePath)) {
      console.error(
        `genai-import-inventory: baseline file not found at ` +
          `${BASELINE_RELATIVE_PATH}. Run without --check to generate it.`,
      );
      process.exit(1);
    }
    const checkedIn = readFileSync(baselinePath, 'utf8');
    if (normalizeForCompare(checkedIn) === normalizeForCompare(generated)) {
      console.log(
        'genai-import-inventory: baseline is up to date ' +
          `(${result.entries.length} importers).`,
      );
      return;
    }
    // Print a simple set-diff of the table lines so the developer can see
    // exactly which importers were added/removed/reclassified.
    const expectedTableLines = extractTableLines(checkedIn);
    const actualTableLines = extractTableLines(generated);
    const expectedSet = new Set(expectedTableLines);
    const actualSet = new Set(actualTableLines);
    const removed = expectedTableLines.filter((l) => !actualSet.has(l));
    const added = actualTableLines.filter((l) => !expectedSet.has(l));
    if (removed.length > 0) {
      console.error('genai-import-inventory: removed from baseline:');
      for (const line of removed) {
        console.error('  - ' + line);
      }
    }
    if (added.length > 0) {
      console.error('genai-import-inventory: added vs baseline:');
      for (const line of added) {
        console.error('  + ' + line);
      }
    }
    console.error(
      'genai-import-inventory: baseline drift detected. ' +
        'Run `scripts/genai-import-inventory.ts` (without --check) to ' +
        'regenerate dev-docs/genai-import-baseline.md.',
    );
    process.exit(1);
  }

  writeFileSync(baselinePath, generated, 'utf8');
  console.log(
    'genai-import-inventory: wrote ' +
      `${BASELINE_RELATIVE_PATH} (${result.entries.length} importers).`,
  );
}

/**
 * Normalize markdown content for comparison: collapse trailing whitespace per
 * line and collapse trailing newlines so cosmetic editor reformatting does
 * not cause spurious drift.
 *
 * Implemented with simple, linear scans (split + trimEnd per line) rather than
 * regex backtracking anchors to satisfy the repo's slow-regex guard.
 */
function normalizeForCompare(content: string): string {
  const trimmedLines = content.split('\n').map(trimTrailingSpaces);
  let last = trimmedLines.length;
  while (last > 0 && trimmedLines[last - 1] === '') {
    last -= 1;
  }
  return trimmedLines.slice(0, last).join('\n') + '\n';
}

/**
 * Remove trailing space/tab characters from a single line. Uses a plain
 * character loop instead of a regex so the repo's slow-regex guard is
 * satisfied (no quantifier-anchor backtracking).
 */
function trimTrailingSpaces(line: string): string {
  let end = line.length;
  while (end > 0) {
    const ch = line.charCodeAt(end - 1);
    if (ch !== 32 && ch !== 9) {
      break;
    }
    end -= 1;
  }
  return line.slice(0, end);
}

/**
 * Extract the data rows (not header/separator) from the markdown table in a
 * rendered baseline document. Used to produce a simple set-diff on baseline
 * drift so the developer sees exactly which importers changed.
 */
function extractTableLines(content: string): string[] {
  const lines = content.split('\n');
  const tableLines: string[] = [];
  let inTable = false;
  for (const line of lines) {
    const trimmed = line.trimStart();
    const isTableRow = trimmed.startsWith('| ');
    if (inTable && !isTableRow) {
      // First non-table line ends the table.
      return tableLines;
    }
    if (isTableRow) {
      inTable = true;
      // Skip the header row and the separator row (dashes).
      const isHeader =
        trimmed.includes('---') ||
        (trimmed.includes('File') && trimmed.includes('Owner'));
      if (!isHeader) {
        tableLines.push(trimTrailingSpaces(line));
      }
    }
  }
  return tableLines;
}

if (
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main();
}
