/**
 * @license
 * Copyright 2025 Vybestack LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Compatibility shim: re-exports telemetry types and functions from
 * the @vybestack/llxprt-code-telemetry package. Avoids re-exporting
 * names that collide with core's own types (e.g., ToolCall, HookEventName).
 */
export {
  TelemetryTarget,
  DEFAULT_TELEMETRY_TARGET,
  DEFAULT_OTLP_ENDPOINT,
  initializeTelemetry,
  shutdownTelemetry,
  isTelemetrySdkInitialized,
  flushTelemetry,
  logCliConfiguration,
  logUserPrompt,
  logToolCall,
  logHookCall,
  logApiRequest,
  logApiError,
  logApiResponse,
  logSlashCommand,
  logKittySequenceOverflow,
  logLoopDetected,
  logNextSpeakerCheck,
  logToolOutputTruncated,
  logFileOperation,
  logConversationRequest,
  logConversationResponse,
  logProviderSwitch,
  logProviderCapability,
  logTokenUsage,
  logPerformanceMetrics,
  logMalformedJsonResponse,
  logModelRouting,
  logExtensionInstallEvent,
  logExtensionUninstall,
  logExtensionEnable,
  logExtensionDisable,
  StartSessionEvent,
  EndSessionEvent,
  UserPromptEvent,
  ToolCallEvent,
  HookCallEvent,
  ApiRequestEvent,
  ApiErrorEvent,
  ApiResponseEvent,
  SlashCommandEvent,
  KittySequenceOverflowEvent,
  LoopDetectedEvent,
  LoopType,
  NextSpeakerCheckEvent,
  MalformedJsonResponseEvent,
  ConversationRequestEvent,
  ConversationResponseEvent,
  EnhancedConversationResponseEvent,
  ProviderSwitchEvent,
  ProviderCapabilityEvent,
  TokenUsageEvent,
  PerformanceMetricsEvent,
  ToolOutputTruncatedEvent,
  FileOperationEvent,
  ModelRoutingEvent,
  ExtensionInstallEvent,
  ExtensionUninstallEvent,
  ExtensionEnableEvent,
  ExtensionDisableEvent,
  IdeConnectionType,
  IdeConnectionEvent,
  ToolCallDecision,
  getDecisionFromOutcome,
  initializeMetrics,
  recordToolCallMetrics,
  recordTokenUsageMetrics,
  recordApiResponseMetrics,
  recordApiErrorMetrics,
  recordFileOperationMetric,
  recordModelRoutingMetrics,
  getMeter,
  SpanStatusCode,
  ValueType,
  SemanticAttributes,
} from '@vybestack/llxprt-code-telemetry/telemetry/index.js';

export type {
  TelemetryEvent,
  ProviderCapabilities,
  ProviderContext,
  ProviderPerformanceMetrics,
  TelemetryConfig,
  SessionConfig,
  TelemetryPromptConfig,
  CompletedToolCallShape,
} from '@vybestack/llxprt-code-telemetry/telemetry/index.js';

export * from './uiTelemetry.js';
